# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(blank=True, default='', max_length=255)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('severity', models.CharField(blank=True, default='', max_length=255)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_alert_rule',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dashboard_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('dashboard_name', models.CharField(blank=True, default='', max_length=255)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('dashboard_type', models.CharField(blank=True, default='', max_length=255)),
                ('realtime_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'analytics_dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('can_customize', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_dashboard_role',
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('kpi_name', models.CharField(blank=True, default='', max_length=255)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_unit', models.CharField(blank=True, default='', max_length=255)),
                ('aggregation_method', models.CharField(blank=True, default='', max_length=255)),
                ('source_entity', models.CharField(blank=True, default='', max_length=255)),
                ('formula_expression', models.CharField(blank=True, default='', max_length=255)),
                ('period_type', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_kpi_definition',
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('health_status', models.CharField(blank=True, default='', max_length=255)),
                ('dimension_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_kpi_result',
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('warning_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('critical_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'analytics_kpi_target',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_code', models.CharField(blank=True, default='', max_length=255)),
                ('widget_name', models.CharField(blank=True, default='', max_length=255)),
                ('widget_type', models.CharField(blank=True, default='', max_length=255)),
                ('data_source_type', models.CharField(blank=True, default='', max_length=255)),
                ('data_source_name', models.CharField(blank=True, default='', max_length=255)),
                ('filter_json', models.JSONField(blank=True, default=dict)),
                ('layout_json', models.JSONField(blank=True, default=dict)),
                ('refresh_seconds', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_widget',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_entity_id', models.UUIDField(blank=True, null=True)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('severity', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('acknowledged_by', models.ForeignKey(blank=True, db_column='acknowledged_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertevent_acknowledged_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_alert_event',
            },
        ),
    ]
