# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_initial'),
        ('analytics', '0002_initial'),
        ('core', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertevent_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertevent_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertrule_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='alert_rule',
            field=models.ForeignKey(blank=True, db_column='alert_rule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertevent_alert_rule_set', to='analytics.alertrule'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_dashboard_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_dashboard_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardrole',
            name='dashboard',
            field=models.ForeignKey(blank=True, db_column='dashboard_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_dashboardrole_dashboard_set', to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardrole',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_dashboardrole_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpidefinition_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='kpi_definition',
            field=models.ForeignKey(blank=True, db_column='kpi_definition_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_alertrule_kpi_definition_set', to='analytics.kpidefinition'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpiresult_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='kpi_definition',
            field=models.ForeignKey(blank=True, db_column='kpi_definition_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpiresult_kpi_definition_set', to='analytics.kpidefinition'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpiresult_organization_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpiresult_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpiresult_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpitarget_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='kpi_definition',
            field=models.ForeignKey(blank=True, db_column='kpi_definition_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpitarget_kpi_definition_set', to='analytics.kpidefinition'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpitarget_organization_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpitarget_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_kpitarget_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='widget',
            name='dashboard',
            field=models.ForeignKey(blank=True, db_column='dashboard_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_widget_dashboard_set', to='analytics.dashboard'),
        ),
    ]
