"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Bold, CalendarDays, Check, CheckCircle2, Clock3, FileDown, FileText, Italic, Link2, MapPin, Pencil, Plus, Save, Strikethrough, Trash2, UserCircle2, X } from "lucide-react";
import toast from "react-hot-toast";
import { MeetingDetail, MeetingRequestSummary, requestApi } from "@/lib/api/request.api";
import { useAuth } from "@/contexts/AuthContext";

type Member = { id: string; name: string; email: string; role: string };
type CreateForm = { title:string; description:string; date:string; startTime:string; endTime:string; location:string; meetingUrl:string; meetingType:string; assigneeId:string; notetakerId:string; participantIds:string[]; agenda:string };
const initialCreate: CreateForm = { title:"",description:"",date:"",startTime:"",endTime:"",location:"",meetingUrl:"",meetingType:"MEETING",assigneeId:"",notetakerId:"",participantIds:[],agenda:"" };
const initialMinutes = { summary:"",opening_notes:"",general_discussion:"",conclusion:"",decisions:"",action_items:"" };

function localIso(date:string,time:string){const value=new Date(`${date}T${time}`);if(Number.isNaN(value.getTime()))throw new Error("Waktu tidak valid");return value.toISOString();}
function displayDate(value:string){return new Date(value).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"});}
function richTextToPlainText(value:string){
  if(typeof window!=="undefined"){
    const container=document.createElement("div");
    container.innerHTML=value;
    return (container.textContent??"").trim();
  }
  return value.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
}

export default function RequestsClient(){
  const {user}=useAuth();
  const [meetings,setMeetings]=useState<MeetingRequestSummary[]>([]);
  const [members,setMembers]=useState<Member[]>([]);
  const [selected,setSelected]=useState<MeetingDetail|null>(null);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [createOpen,setCreateOpen]=useState(false);
  const [notesOpen,setNotesOpen]=useState(false);
  const [createForm,setCreateForm]=useState<CreateForm>(initialCreate);
  const [minutes,setMinutes]=useState(initialMinutes);
  const [personInCharge,setPersonInCharge]=useState("");

  const openMeeting=useCallback(async(id:string)=>{try{const detail=await requestApi.getMeeting(id);setSelected(detail);setPersonInCharge(detail.request?.assignee_user_id??detail.notetaker_user_id??"");setMinutes({summary:detail.minutes?.summary??"",opening_notes:detail.minutes?.opening_notes??"",general_discussion:markdownToRichText(detail.minutes?.general_discussion??""),conclusion:detail.minutes?.conclusion??"",decisions:detail.minutes?.decisions.map(item=>item.decision_text).join("\n")??"",action_items:detail.minutes?.action_items.map(item=>item.title).join("\n")??""});}catch{toast.error("Detail meeting tidak dapat dimuat.");}},[]);
  const load=useCallback(async()=>{setLoading(true);try{const [rows,team]=await Promise.all([requestApi.listMeetings(),requestApi.listTeamMembers()]);setMeetings(rows);setMembers(team);const id=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("meeting"):null;if(id)await openMeeting(id);}catch{toast.error("Meeting Request tidak dapat dimuat.");}finally{setLoading(false);}},[openMeeting]);
  useEffect(()=>{void load();},[load]);

  async function submitMeeting(event:FormEvent,draft:boolean){event.preventDefault();if(!createForm.notetakerId){toast.error("Pilih notulis sebelum menyimpan Meeting Request.");return;}setBusy(true);try{const ids=new Set(createForm.participantIds);ids.add(createForm.notetakerId);await requestApi.createMeeting({title:createForm.title,description:createForm.description,start_at:localIso(createForm.date,createForm.startTime),end_at:localIso(createForm.date,createForm.endTime),location:createForm.location,meeting_url:createForm.meetingUrl,meeting_type:"INTERNAL",assignee_user_id:createForm.assigneeId||undefined,notetaker_user_id:createForm.notetakerId,is_draft:draft,tagged_users:Array.from(ids).map(id=>({id,name:members.find(member=>member.id===id)?.name??id})),agenda_items:createForm.agenda.split("\n").map(title=>title.trim()).filter(Boolean).map(title=>({title}))});toast.success(draft?"Draft request berhasil disimpan.":"Meeting Request terkirim dan peserta telah diberi notifikasi.");setCreateOpen(false);setCreateForm(initialCreate);await load();}catch{toast.error("Gagal menyimpan request. Periksa tanggal, waktu, dan data wajib.");}finally{setBusy(false);}}
  async function reassign(){if(!selected?.request||!personInCharge)return toast.error("Pilih person in charge.");setBusy(true);try{await requestApi.assignRequest(selected.request.id,personInCharge);toast.success("Person in charge diperbarui.");await openMeeting(selected.id);}catch{toast.error("Role aktif tidak memiliki izin reassign.");}finally{setBusy(false);}}
  const minutesPayload=useMemo(()=>({summary:minutes.summary||richTextToPlainText(minutes.general_discussion).split("\n")[0]||"Notulensi meeting",opening_notes:minutes.opening_notes,general_discussion:minutes.general_discussion,conclusion:minutes.conclusion,decisions:minutes.decisions.split("\n").map(text=>text.trim()).filter(Boolean).map(text=>({text})),action_items:minutes.action_items.split("\n").map(title=>title.trim()).filter(Boolean).map(title=>({title}))}),[minutes]);
  async function saveNotes(publish=false){if(!selected)return;if(!selected.permissions?.can_edit_minutes&&String(selected.notetaker_user_id)!==String(user?.id)){toast.error("Hanya notulis yang ditugaskan yang dapat mengubah notulensi.");return;}setBusy(true);try{let detail=await requestApi.saveMinutes(selected.id,minutesPayload);if(publish)detail=await requestApi.publishMinutes(selected.id);setSelected(detail);setNotesOpen(false);toast.success(publish?"Notulensi dipublikasikan dan tindak lanjut dihasilkan.":"Notulensi berhasil disimpan.");await load();}catch{toast.error("Notulensi gagal disimpan. Pastikan Anda adalah notulis yang ditugaskan.");}finally{setBusy(false);}}

  return <div className="min-h-[calc(100vh-120px)] bg-[#FDFDFD] text-[#090909]">
    <div className="rounded-[24px] border border-[#E5E5E5] bg-white p-5 sm:p-7">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#4F5050]">Contents / Request</p><h1 className="mt-2 text-2xl font-extrabold text-[#294BB2]">Ticket Request</h1><p className="mt-1 text-sm text-[#4F5050]">Kelola permintaan meeting, peserta, dan notulensi dalam satu alur.</p></div><button onClick={()=>setCreateOpen(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#294BB2] px-5 text-sm font-bold text-white hover:bg-[#203d91]"><Plus size={18}/> New Ticket Request</button></div>
      <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {loading&&[1,2,3].map(item=><div key={item} className="h-48 animate-pulse rounded-[18px] border border-[#E5E5E5] bg-[#FDFDFD] p-5"><div className="h-4 w-1/3 rounded bg-[#EAF6FF]"/><div className="mt-5 h-4 w-4/5 rounded bg-[#EFEFEF]"/><div className="mt-3 h-3 w-3/5 rounded bg-[#EFEFEF]"/></div>)}
        {!loading&&meetings.length===0&&<div className="col-span-full rounded-[18px] border border-dashed border-[#D9D9D9] p-14 text-center text-sm text-[#4F5050]">Belum ada Meeting Request.</div>}
        {meetings.map(row=><button key={row.id} onClick={()=>void openMeeting(row.id)} className="group rounded-[18px] border border-[#D9D9D9] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[#294BB2] hover:shadow-md"><div className="flex items-center justify-between"><span className="rounded-xl bg-[#294BB2] px-4 py-2 text-xs font-bold tracking-wide text-white">MEETING</span><span className="rounded-xl bg-[#EAF6FF] px-3 py-2 text-xs font-bold text-[#294BB2]">{row.status}</span></div><h2 className="mt-5 line-clamp-2 text-lg font-extrabold text-[#294BB2]">{row.request?.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#4F5050]">{row.request?.description||"Tanpa deskripsi"}</p><div className="mt-5 flex items-center justify-between border-t border-[#EFEFEF] pt-4 text-xs text-[#4F5050]"><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{displayDate(row.start_at)}</span><ArrowRight size={16} className="text-[#294BB2] transition group-hover:translate-x-1"/></div></button>)}
      </div>
    </div>
    {createOpen&&<CreateRequestModal form={createForm} setForm={setCreateForm} members={members} busy={busy} onClose={()=>setCreateOpen(false)} onSubmit={submitMeeting}/>}
    {selected&&!notesOpen&&<MeetingDetailModal detail={selected} currentUserId={user?.id} members={members} personInCharge={personInCharge} setPersonInCharge={setPersonInCharge} busy={busy} onClose={()=>setSelected(null)} onReassign={reassign} onNotes={()=>setNotesOpen(true)}/>}
    {selected&&notesOpen&&<NotesModal detail={selected} minutes={minutes} setMinutes={setMinutes} busy={busy} onClose={()=>setNotesOpen(false)} onSave={saveNotes}/>}
  </div>;
}

function ModalBackdrop({children,wide=false}:{children:React.ReactNode;wide?:boolean}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#090909]/30 p-3 backdrop-blur-[1px]"><div className={`max-h-[76vh] w-full overflow-y-auto rounded-[24px] bg-white shadow-2xl sm:w-[80vw] ${wide?"max-w-[928px]":"max-w-[784px]"}`}>{children}</div></div>;}

function CreateRequestModal({form,setForm,members,busy,onClose,onSubmit}:{form:CreateForm;setForm:(form:CreateForm)=>void;members:Member[];busy:boolean;onClose:()=>void;onSubmit:(event:FormEvent,draft:boolean)=>void}){const [draft,setDraft]=useState(false);return <ModalBackdrop wide><form onSubmit={event=>onSubmit(event,draft)} className="grid min-h-[520px] gap-6 p-6 sm:p-8 lg:grid-cols-[2fr_1fr]">
  <section><button type="button" onClick={onClose} className="mb-10 inline-flex items-center gap-4 text-xl font-extrabold text-[#294BB2]"><ArrowLeft size={20}/> New Ticket Request</button><div className="grid gap-5 md:grid-cols-[1.15fr_.75fr_.75fr]"><SelectField label="Request Type" value={form.meetingType} onChange={value=>setForm({...form,meetingType:value})}><option value="MEETING">Meeting</option></SelectField><Field label="Time" type="time" required value={form.startTime} onChange={value=>setForm({...form,startTime:value})}/><Field label="End" type="time" required value={form.endTime} onChange={value=>setForm({...form,endTime:value})}/></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Date" type="date" required value={form.date} onChange={value=>setForm({...form,date:value})}/><Field label="Location" value={form.location} onChange={value=>setForm({...form,location:value})}/></div><label className="mt-5 block text-sm font-bold text-[#294BB2]">Meeting Link<div className="mt-2 flex h-11 items-center gap-3 rounded-xl border border-[#D9D9D9] px-4"><Link2 size={17}/><input type="url" value={form.meetingUrl} onChange={event=>setForm({...form,meetingUrl:event.target.value})} placeholder="Add meeting link" className="min-w-0 flex-1 outline-none"/></div></label><div className="mt-8 space-y-5"><Field label="Ticket Title" required value={form.title} onChange={value=>setForm({...form,title:value})}/><TextArea label="Request Details" rows={7} value={form.description} onChange={value=>setForm({...form,description:value})}/><TextArea label="Agenda — one item per line" rows={4} value={form.agenda} onChange={value=>setForm({...form,agenda:value})}/></div></section>
  <aside className="flex flex-col"><div className="space-y-7"><SelectField icon={<UserCircle2 size={22}/>} label="Assign team" value={form.assigneeId} onChange={value=>setForm({...form,assigneeId:value})}><option value="">Pilih Staff</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</SelectField><SelectField icon={<FileText size={22}/>} label="Notulis *" value={form.notetakerId} onChange={value=>setForm({...form,notetakerId:value})}><option value="">Pilih notulis</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</SelectField><InvitePeoplePicker members={members} selectedIds={form.participantIds} onChange={participantIds=>setForm({...form,participantIds})}/></div><div className="mt-auto space-y-3 pt-10"><button disabled={busy} onClick={()=>setDraft(false)} className="flex h-12 w-full items-center justify-center gap-3 rounded-xl bg-[#294BB2] font-bold text-white disabled:opacity-50">Send Request <ArrowRight size={18}/></button><button disabled={busy} onClick={()=>setDraft(true)} className="flex h-12 w-full items-center justify-center gap-3 rounded-xl border-2 border-[#3154C7] font-bold text-[#294BB2] disabled:opacity-50">Simpan Request <FileDown size={18}/></button></div></aside>
</form></ModalBackdrop>;}

function MeetingDetailModal({detail,currentUserId,members,personInCharge,setPersonInCharge,busy,onClose,onReassign,onNotes}:{detail:MeetingDetail;currentUserId?:string|number;members:Member[];personInCharge:string;setPersonInCharge:(id:string)=>void;busy:boolean;onClose:()=>void;onReassign:()=>void;onNotes:()=>void}){
  const hasMinutes=Boolean(detail.minutes);
  const published=detail.minutes?.status==="PUBLISHED";
  const canEditMinutes=detail.permissions?.can_edit_minutes??String(detail.notetaker_user_id)===String(currentUserId);
  const canOpenMinutes=published||canEditMinutes;
  const notetaker=detail.notetaker??detail.participants.find(item=>item.user_id===detail.notetaker_user_id)?.user??null;
  const notetakerName=notetaker?.full_name??notetaker?.email??"Belum ditentukan";
  const notesLabel=published?"Lihat Notulensi":canEditMinutes?(hasMinutes?"Edit Notulensi":"Tambah Notulensi"):"Khusus Notulis";
  return <ModalBackdrop><div>
    <header className="flex items-center justify-between rounded-t-[24px] bg-[#EAF6FF] px-6 py-5 sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#5670B9]">Meeting Request</p><h2 className="mt-1 text-xl font-extrabold text-[#294BB2]">Scheduled Meeting</h2></div><button onClick={onClose} aria-label="Tutup detail meeting" className="grid h-10 w-10 place-items-center rounded-full text-[#294BB2] transition hover:bg-white"><X size={23}/></button></header>
    <div className="p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><span className="rounded-lg bg-[#294BB2] px-4 py-2 text-xs font-bold tracking-wide text-white">MEETING</span><span className="rounded-lg bg-[#EAF6FF] px-4 py-2 text-xs font-bold text-[#294BB2]">{detail.request?.status??detail.status}</span></div>
      <h3 className="mt-6 text-2xl font-extrabold text-[#294BB2]">{detail.request?.title}</h3><p className="mt-2 text-sm leading-6 text-[#4F5050]">{detail.request?.description||"Tanpa deskripsi"}</p>
      <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#4F5050]"><span className="flex items-center gap-2"><Clock3 size={17}/>{displayDate(detail.start_at)}</span>{detail.location&&<span className="flex items-center gap-2"><MapPin size={17}/>{detail.location}</span>}</div>
      <div className="mt-7 rounded-2xl border border-[#E5E5E5] p-5"><label className="block text-xs font-extrabold tracking-wide text-[#294BB2]">PERSON IN CHARGE<div className="mt-2 flex flex-col gap-3 sm:flex-row"><select value={personInCharge} onChange={event=>setPersonInCharge(event.target.value)} className="h-11 min-w-0 flex-1 rounded-xl border border-[#D9D9D9] bg-white px-4 text-sm outline-none focus:border-[#294BB2]"><option value="">Pilih staff</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select><button disabled={busy||!personInCharge} onClick={onReassign} className="h-11 rounded-xl bg-[#294BB2] px-6 text-sm font-bold text-white transition hover:bg-[#203D91] disabled:opacity-50">Reassign</button></div></label></div>
      <section className="mt-4 flex flex-col gap-3 rounded-2xl border border-[#CFE0F5] bg-[#F5FAFF] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold tracking-wide text-[#294BB2]">NOTULIS</p><p className="mt-1 text-xs text-[#6B7280]">Satu-satunya pengguna yang dapat menyusun dan mempublikasikan notulensi.</p></div><div className="inline-flex items-center gap-2 self-start rounded-xl bg-white px-3 py-2 text-sm font-bold text-[#294BB2] shadow-sm sm:self-auto"><FileText size={17}/><span>{notetakerName}</span>{canEditMinutes&&<span className="rounded-md bg-[#294BB2] px-2 py-0.5 text-[10px] text-white">ANDA</span>}</div></section>
      <div className="mt-5 grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-[#E5E5E5] p-5"><p className="text-xs font-extrabold tracking-wide text-[#294BB2]">INVITED PEOPLE</p><div className="mt-3 flex flex-wrap gap-2">{detail.participants.filter(item=>item.participant_role!=="ORGANIZER").map(item=><span key={item.id} className="inline-flex items-center gap-2 rounded-lg bg-[#EAF6FF] px-3 py-2 text-xs font-bold text-[#294BB2]"><UserCircle2 size={17}/>{item.user?.full_name??item.user?.email??"Team member"}</span>)}</div></section><section className="rounded-2xl border border-[#E5E5E5] p-5"><p className="text-xs font-extrabold tracking-wide text-[#294BB2]">MEETING LINK</p><div className="mt-3 flex h-10 items-center rounded-xl bg-[#F8FAFC] px-3"><span className="min-w-0 flex-1 truncate text-sm text-[#4F5050]">{detail.meeting_url||"Belum ada meeting link"}</span><Pencil size={18} className="text-[#1687EF]"/></div></section></div>
      <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:items-end sm:justify-between"><button onClick={onClose} className="h-11 rounded-xl px-5 text-sm font-semibold text-[#4F5050] transition hover:bg-[#F4F4F4]">Tutup</button><div className="text-right">{!canOpenMinutes&&<p className="mb-2 text-xs text-[#6B7280]">Hanya {notetakerName} yang dapat membuka editor notulensi.</p>}<button disabled={!canOpenMinutes} onClick={onNotes} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#294BB2] px-6 text-sm font-bold text-white transition hover:bg-[#203D91] disabled:cursor-not-allowed disabled:bg-[#AAB8DF]"><FileText size={18}/>{notesLabel}</button></div></div>
    </div>
  </div></ModalBackdrop>;
}

const richTextTags=new Set(["B","STRONG","I","EM","S","STRIKE","BR","DIV","P","UL","OL","LI"]);
function sanitizeRichText(value:string){
  if(typeof window==="undefined")return value;
  const template=document.createElement("template");
  template.innerHTML=value;
  template.content.querySelectorAll("script,style,iframe,object,embed").forEach(node=>node.remove());
  Array.from(template.content.querySelectorAll("*")).reverse().forEach(element=>{
    if(richTextTags.has(element.tagName))Array.from(element.attributes).forEach(attribute=>element.removeAttribute(attribute.name));
    else element.replaceWith(...Array.from(element.childNodes));
  });
  return template.innerHTML;
}
function markdownToRichText(value:string){
  if(!value)return "";
  if(/<\/?[a-z][\s\S]*>/i.test(value))return sanitizeRichText(value);
  const escaped=value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  return escaped.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/~~(.+?)~~/g,"<s>$1</s>").replace(/(^|\s)_([^_\n]+)_(?=\s|$)/g,"$1<em>$2</em>").replace(/\r?\n/g,"<br>");
}
function normalizedEditorHtml(element:HTMLDivElement){
  const html=sanitizeRichText(element.innerHTML).replace(/^(<br>)+|(<br>)+$/g,"");
  return richTextToPlainText(html)?html:"";
}

function RichTextEditor({value,onChange,disabled}:{value:string;onChange:(value:string)=>void;disabled:boolean}){
  const editorRef=useRef<HTMLDivElement>(null);
  const [active,setActive]=useState({bold:false,italic:false,strikeThrough:false});
  const [empty,setEmpty]=useState(!richTextToPlainText(value));
  useEffect(()=>{const editor=editorRef.current;if(!editor)return;const incoming=sanitizeRichText(value);if(sanitizeRichText(editor.innerHTML)!==incoming)editor.innerHTML=incoming;setEmpty(!richTextToPlainText(incoming));},[value]);
  useEffect(()=>{const update=()=>{const selection=document.getSelection();if(!editorRef.current||!selection?.anchorNode||!editorRef.current.contains(selection.anchorNode))return;setActive({bold:document.queryCommandState("bold"),italic:document.queryCommandState("italic"),strikeThrough:document.queryCommandState("strikeThrough")});};document.addEventListener("selectionchange",update);return()=>document.removeEventListener("selectionchange",update);},[]);
  const emitChange=()=>{const editor=editorRef.current;if(!editor)return;const next=normalizedEditorHtml(editor);setEmpty(!richTextToPlainText(next));onChange(next);};
  const format=(command:"bold"|"italic"|"strikeThrough")=>{if(disabled)return;editorRef.current?.focus();document.execCommand(command,false);emitChange();setActive(old=>({...old,[command]:document.queryCommandState(command)}));};
  const formats:["bold"|"italic"|"strikeThrough",string,React.ReactNode][]=[["bold","Tebal",<Bold key="bold" size={18}/>],["italic","Miring",<Italic key="italic" size={18}/>],["strikeThrough","Coret",<Strikethrough key="strike" size={18}/>]];
  return <section className="flex min-h-[360px] flex-col overflow-hidden rounded-2xl border border-[#D9D9D9] bg-white focus-within:border-[#294BB2] focus-within:ring-2 focus-within:ring-[#294BB2]/10 lg:min-h-0">
    <div className="flex items-center justify-between border-b border-[#E5E5E5] bg-[#F8FAFC] px-3 py-2"><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#294BB2]">Catatan Utama</p><p className="mt-0.5 text-xs text-[#6B7280]">Pilih teks, lalu gunakan format.</p></div><div className="flex items-center gap-1 rounded-xl border border-[#DDE7F2] bg-white p-1" role="toolbar" aria-label="Format teks">{formats.map(([command,label,icon])=><button key={command} type="button" title={label} aria-label={label} aria-pressed={active[command]} disabled={disabled} onMouseDown={event=>event.preventDefault()} onClick={()=>format(command)} className={`grid h-9 w-9 place-items-center rounded-lg transition disabled:cursor-not-allowed disabled:opacity-40 ${active[command]?"bg-[#294BB2] text-white":"text-[#294BB2] hover:bg-[#EAF6FF]"}`}>{icon}</button>)}</div></div>
    <div className="relative min-h-0 flex-1"><div ref={editorRef} contentEditable={!disabled} suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="Isi notulensi meeting" onInput={emitChange} onBlur={()=>{const editor=editorRef.current;if(editor){const clean=normalizedEditorHtml(editor);editor.innerHTML=clean;onChange(clean);}}} className={`h-full min-h-[300px] overflow-y-auto p-5 text-base leading-7 outline-none sm:p-6 ${disabled?"cursor-default bg-[#FAFAFA]":""}`}/>{empty&&<span className="pointer-events-none absolute left-5 top-5 text-sm text-[#9CA3AF] sm:left-6 sm:top-6">Tulis pembahasan meeting di sini...</span>}</div>
  </section>;
}

function NotesModal({detail,minutes,setMinutes,busy,onClose,onSave}:{detail:MeetingDetail;minutes:typeof initialMinutes;setMinutes:React.Dispatch<React.SetStateAction<typeof initialMinutes>>;busy:boolean;onClose:()=>void;onSave:(publish?:boolean)=>void}){
  const published=detail.minutes?.status==="PUBLISHED";
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#090909]/35 p-2 backdrop-blur-[1px] sm:p-4"><div className="flex max-h-[80vh] min-h-0 w-full max-w-[1008px] flex-col overflow-hidden rounded-[22px] bg-white shadow-2xl sm:w-[80vw]">
    <header className="flex shrink-0 items-center justify-between gap-4 border-b border-[#EAEAEA] px-4 py-4 sm:px-7"><button onClick={onClose} className="inline-flex min-w-0 items-center gap-3 text-left text-lg font-extrabold text-[#294BB2]"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#EAF6FF]"><ArrowLeft size={18}/></span><span className="truncate">{detail.request?.title}</span></button>{published?<span className="rounded-lg bg-[#EAF6FF] px-4 py-2 text-xs font-extrabold text-[#294BB2]">DIPUBLIKASIKAN</span>:<button disabled={busy} onClick={()=>void onSave(false)} className="inline-flex h-10 shrink-0 items-center gap-2 rounded-xl bg-[#294BB2] px-4 text-sm font-bold text-white transition hover:bg-[#203D91] disabled:opacity-50 sm:px-6"><Save size={18}/><span className="hidden sm:inline">Simpan Draft</span><span className="sm:hidden">Simpan</span></button>}</header>
    {published&&<div className="mx-4 mt-4 rounded-xl border border-[#CFE3F6] bg-[#F1F8FE] px-4 py-3 text-sm text-[#294BB2] sm:mx-7">Notulensi ini telah dipublikasikan dan ditampilkan dalam mode baca.</div>}
    <div className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 sm:p-7 lg:grid-cols-[minmax(0,1.8fr)_minmax(300px,1fr)] lg:overflow-hidden"><RichTextEditor disabled={published} value={minutes.general_discussion} onChange={value=>setMinutes(old=>({...old,general_discussion:value}))}/><aside className="grid content-start gap-4 overflow-visible lg:overflow-y-auto lg:pr-1"><div className="rounded-2xl border border-[#E5E5E5] bg-[#FCFCFC] p-4"><TextArea disabled={published} label="Ringkasan" hint="Gambaran singkat hasil meeting" rows={3} value={minutes.summary} onChange={value=>setMinutes(old=>({...old,summary:value}))}/></div><div className="rounded-2xl border border-[#E5E5E5] bg-[#FCFCFC] p-4"><TextArea disabled={published} label="Keputusan" hint="Tulis satu keputusan per baris" rows={4} value={minutes.decisions} onChange={value=>setMinutes(old=>({...old,decisions:value}))}/></div><div className="rounded-2xl border border-[#E5E5E5] bg-[#FCFCFC] p-4"><TextArea disabled={published} label="Action Item" hint="Tulis satu tindak lanjut per baris" rows={4} value={minutes.action_items} onChange={value=>setMinutes(old=>({...old,action_items:value}))}/></div></aside></div>
    <footer className="flex shrink-0 flex-wrap items-center justify-end gap-2 border-t border-[#EAEAEA] bg-white px-4 py-3 sm:px-7">{!published&&<><button disabled={busy} onClick={()=>{if(window.confirm("Hapus seluruh isi draft notulensi?"))setMinutes(initialMinutes)}} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#FFF0F0] px-4 text-sm font-bold text-[#A50E0E] transition hover:bg-[#FFDCDC] disabled:opacity-50"><Trash2 size={17}/>Hapus Isi</button><button disabled={busy} onClick={()=>void onSave(true)} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#294BB2] px-4 text-sm font-bold text-[#294BB2] transition hover:bg-[#EAF6FF] disabled:opacity-50"><CheckCircle2 size={17}/>Publikasikan</button></>}</footer>
  </div></div>;
}

function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm font-bold text-[#294BB2]">{label}<input required={required} type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#D9D9D9] px-4 text-[#4F5050] outline-none focus:border-[#3154C7]"/></label>;}
function SelectField({label,value,onChange,children,icon}:{label:string;value:string;onChange:(value:string)=>void;children:React.ReactNode;icon?:React.ReactNode}){return <label className="block text-sm font-bold text-[#4F5050]"><span className="mb-2 flex items-center gap-3">{icon&&<span className="text-[#1687EF]">{icon}</span>}{label}</span><select value={value} onChange={event=>onChange(event.target.value)} className="h-11 w-full rounded-xl border-2 border-[#3154C7] bg-white px-4 text-[#294BB2] outline-none">{children}</select></label>;}
function InvitePeoplePicker({members,selectedIds,onChange}:{members:Member[];selectedIds:string[];onChange:(ids:string[])=>void}){const selected=new Set(selectedIds);const toggle=(id:string)=>onChange(selected.has(id)?selectedIds.filter(item=>item!==id):[...selectedIds,id]);return <fieldset><legend className="flex w-full items-center justify-between gap-3 text-sm font-bold text-[#4F5050]"><span className="flex items-center gap-3"><Link2 size={22} className="text-[#1687EF]"/>Invite people</span>{selectedIds.length>0&&<button type="button" onClick={()=>onChange([])} className="text-xs font-semibold text-[#294BB2] hover:underline">Hapus semua</button>}</legend><p className="mt-2 text-xs font-normal leading-5 text-[#6B7280]">Klik nama anggota untuk memilih. Anda dapat memilih lebih dari satu orang.</p><div className="mt-3 max-h-52 space-y-1 overflow-y-auto rounded-[18px] border-2 border-[#3154C7] bg-white p-2" role="group" aria-label="Pilih anggota yang akan diundang">{members.length===0?<p className="px-3 py-5 text-center text-xs text-[#6B7280]">Belum ada anggota tim aktif.</p>:members.map(member=>{const checked=selected.has(member.id);return <button key={member.id} type="button" role="checkbox" aria-checked={checked} onClick={()=>toggle(member.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${checked?"bg-[#294BB2] text-white":"text-[#294BB2] hover:bg-[#EAF6FF]"}`}><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border-2 ${checked?"border-white bg-white text-[#294BB2]":"border-[#3154C7] bg-white"}`}>{checked&&<Check size={14} strokeWidth={3}/>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{member.name}</strong><span className={`block truncate text-xs font-normal ${checked?"text-blue-100":"text-[#6B7280]"}`}>{member.role} · {member.email}</span></span></button>})}</div><div className="mt-2 flex items-center justify-between text-xs"><span className={selectedIds.length?"font-bold text-[#294BB2]":"text-[#6B7280]"}>{selectedIds.length} anggota dipilih</span>{selectedIds.length>0&&<span className="text-[#6B7280]">Klik lagi untuk membatalkan</span>}</div></fieldset>;}
function TextArea({label,value,onChange,rows,hint,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;rows:number;hint?:string;disabled?:boolean}){return <label className="block text-sm font-bold text-[#294BB2]">{label}{hint&&<span className="mt-1 block text-xs font-normal text-[#6B7280]">{hint}</span>}<textarea disabled={disabled} rows={rows} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 w-full resize-none rounded-xl border border-[#D9D9D9] bg-white p-3 font-normal leading-6 text-[#4F5050] outline-none focus:border-[#3154C7] disabled:cursor-default disabled:bg-[#FAFAFA]"/></label>;}
