# Generated by Django 5.2.17 on 2026-08-05 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, default='', max_length=255)),
                ('asset_name', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('available_for_use_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('useful_life_months', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'asset_asset',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_type', models.CharField(blank=True, default='', max_length=255)),
                ('depreciation_method', models.CharField(blank=True, default='', max_length=255)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('useful_life_periods', models.IntegerField(blank=True, null=True)),
                ('depreciation_start_date', models.DateField(blank=True, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('net_book_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'asset_book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_code', models.CharField(blank=True, default='', max_length=255)),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'asset_category',
            },
        ),
        migrations.CreateModel(
            name='DepreciationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField(blank=True, null=True)),
                ('opening_book_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('depreciation_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('closing_book_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'asset_depreciation_line',
            },
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('net_book_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'asset_disposal',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(blank=True, default='', max_length=255)),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'asset_maintenance',
            },
        ),
    ]
