# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_category_set', to='master_data.productcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_department_set', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='asset',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_document_set', to='core.businessdocument'),
        ),
    ]
