# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_party',
            field=models.ForeignKey(blank=True, db_column='supplier_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_supplier_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warehouse_location',
            field=models.ForeignKey(blank=True, db_column='warehouse_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset_warehouse_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='book',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_book_asset_set', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='category',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(blank=True, db_column='accumulated_depreciation_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_category_accumulated_depreciation_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='asset_account',
            field=models.ForeignKey(blank=True, db_column='asset_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_category_asset_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_category_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='depreciation_expense_account',
            field=models.ForeignKey(blank=True, db_column='depreciation_expense_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_category_depreciation_expense_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='asset_book',
            field=models.ForeignKey(blank=True, db_column='asset_book_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_depreciationline_asset_book_set', to='assets.book'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_depreciationline_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_depreciationline_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_disposal_asset_set', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_disposal_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_disposal_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_maintenance_asset_set', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_maintenance_machine_set', to='master_data.machine'),
        ),
    ]
