# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'proc_purchase_requisition',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'proc_purchase_requisition_line',
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'proc_rfq',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('evaluation_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'proc_supplier_quotation',
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_variance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('price_variance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_variance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('match_status', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proc_three_way_match',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('inspection_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceipt_document_set', to='core.businessdocument')),
                ('supplier_party', models.ForeignKey(blank=True, db_column='supplier_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceipt_supplier_party_set', to='master_data.party')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceipt_warehouse_set', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'proc_goods_receipt',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('accepted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rejected_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('goods_receipt', models.ForeignKey(blank=True, db_column='goods_receipt_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_goods_receipt_set', to='procurement.goodsreceipt')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_product_set', to='master_data.product')),
                ('serial_number', models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_serial_number_set', to='inventory.serialnumber')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'proc_goods_receipt_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorder_currency_set', to='master_data.currency')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorder_document_set', to='core.businessdocument')),
                ('payment_term', models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorder_payment_term_set', to='master_data.paymentterm')),
                ('supplier_party', models.ForeignKey(blank=True, db_column='supplier_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorder_supplier_party_set', to='master_data.party')),
            ],
            options={
                'db_table': 'proc_purchase_order',
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceipt_purchase_order_set', to='procurement.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('invoiced_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_product_set', to='master_data.product')),
            ],
            options={
                'db_table': 'proc_purchase_order_line',
            },
        ),
    ]
