# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0003_initial'),
        ('master_data', '0001_initial'),
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_purchase_order_set', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_code',
            field=models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_tax_code_set', to='master_data.taxcode'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, db_column='purchase_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_goodsreceiptline_purchase_order_line_set', to='procurement.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisition_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisition_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisition_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisition_requested_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisitionline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='project_material_requirement',
            field=models.ForeignKey(blank=True, db_column='project_material_requirement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisitionline_project_material_requirement_set', to='projects.materialrequirement'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='requisition',
            field=models.ForeignKey(blank=True, db_column='requisition_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisitionline_requisition_set', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisitionline_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaserequisitionline_warehouse_set', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='requisition_line',
            field=models.ForeignKey(blank=True, db_column='requisition_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorderline_requisition_line_set', to='procurement.purchaserequisitionline'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rfq_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='requisition',
            field=models.ForeignKey(blank=True, db_column='requisition_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rfq_requisition_set', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_supplierquotation_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_supplierquotation_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='rfq',
            field=models.ForeignKey(blank=True, db_column='rfq_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_supplierquotation_rfq_set', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='supplier_party',
            field=models.ForeignKey(blank=True, db_column='supplier_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_supplierquotation_supplier_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_quotation',
            field=models.ForeignKey(blank=True, db_column='supplier_quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchaseorder_supplier_quotation_set', to='procurement.supplierquotation'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, db_column='goods_receipt_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_threewaymatch_goods_receipt_set', to='procurement.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_threewaymatch_purchase_order_set', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_threewaymatch_reviewed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, db_column='supplier_invoice_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_threewaymatch_supplier_invoice_set', to='finance.billingdocument'),
        ),
    ]
