# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move_type', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'inv_stock_move',
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'inv_stock_move_line',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'inv_stock_reservation',
            },
        ),
        migrations.CreateModel(
            name='ValuationLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('remaining_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inv_valuation_layer',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(blank=True, default='', max_length=255)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quality_status', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lot_product_set', to='master_data.product')),
            ],
            options={
                'db_table': 'inv_lot',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('current_location', models.ForeignKey(blank=True, db_column='current_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_serialnumber_current_location_set', to='master_data.warehouselocation')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_serialnumber_product_set', to='master_data.product')),
            ],
            options={
                'db_table': 'inv_serial_number',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('reserved_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('inventory_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_company_set', to='core.company')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_product_set', to='master_data.product')),
                ('serial_number', models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_serial_number_set', to='inventory.serialnumber')),
                ('warehouse_location', models.ForeignKey(blank=True, db_column='warehouse_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_warehouse_location_set', to='master_data.warehouselocation')),
            ],
            options={
                'db_table': 'inv_stock_balance',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_date', models.DateField(blank=True, null=True)),
                ('count_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcount_document_set', to='core.businessdocument')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcount_warehouse_set', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inv_stock_count',
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('variance_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcountline_location_set', to='master_data.warehouselocation')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcountline_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcountline_product_set', to='master_data.product')),
                ('stock_count', models.ForeignKey(blank=True, db_column='stock_count_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockcountline_stock_count_set', to='inventory.stockcount')),
            ],
            options={
                'db_table': 'inv_stock_count_line',
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posting_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('value_delta', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('balance_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('balance_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_company_set', to='core.company')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_product_set', to='master_data.product')),
            ],
            options={
                'db_table': 'inv_stock_ledger_entry',
            },
        ),
    ]
