# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_production_order_set', to='manufacturing.productionorder'),
        ),
    ]
