# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_reversal_of_set', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='serial_number',
            field=models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_serial_number_set', to='inventory.serialnumber'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='source_line',
            field=models.ForeignKey(blank=True, db_column='source_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_source_line_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='warehouse_location',
            field=models.ForeignKey(blank=True, db_column='warehouse_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockledgerentry_warehouse_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='last_ledger_entry',
            field=models.ForeignKey(blank=True, db_column='last_ledger_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockbalance_last_ledger_entry_set', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='destination_location',
            field=models.ForeignKey(blank=True, db_column='destination_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_destination_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_location',
            field=models.ForeignKey(blank=True, db_column='source_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmove_source_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmoveline_lot_set', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmoveline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='serial_number',
            field=models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmoveline_serial_number_set', to='inventory.serialnumber'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='stock_move',
            field=models.ForeignKey(blank=True, db_column='stock_move_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmoveline_stock_move_set', to='inventory.stockmove'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockmoveline_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockreservation_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockreservation_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockreservation_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, db_column='sales_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockreservation_sales_order_line_set', to='sales.orderline'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='warehouse_location',
            field=models.ForeignKey(blank=True, db_column='warehouse_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stockreservation_warehouse_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='valuationlayer',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_valuationlayer_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='valuationlayer',
            name='receipt_ledger_entry',
            field=models.ForeignKey(blank=True, db_column='receipt_ledger_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_valuationlayer_receipt_ledger_entry_set', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='valuationlayer',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_valuationlayer_warehouse_set', to='master_data.warehouse'),
        ),
    ]
