# Generated by Django 5.2.17 on 2026-08-05 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSalesDashboard',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('weighted_project_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('win_rate_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('prospect_count', models.IntegerField(blank=True, null=True)),
                ('pitch_count', models.IntegerField(blank=True, null=True)),
                ('closing_count', models.IntegerField(blank=True, null=True)),
                ('offering_margin_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'view_crm_sales_dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceMainDashboard',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('profit_loss_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('net_cashflow_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_unit_hpp', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('active_alert_count', models.IntegerField(blank=True, null=True)),
                ('periodic_kpi_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_finance_main_dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDashboard',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('overall_kpi_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('planned_progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('project_health_status', models.CharField(blank=True, default='', max_length=255)),
                ('overdue_task_count', models.IntegerField(blank=True, null=True)),
                ('unread_notification_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_project_dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTimelineCost',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('machine_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('equipment_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('overhead_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'view_project_timeline_cost',
                'managed': False,
            },
        ),
    ]
