# Generated by Django 5.2.17 on 2026-08-05 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0003_initial'),
        ('manufacturing', '0002_initial'),
        ('master_data', '0001_initial'),
        ('procurement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(blank=True, default='', max_length=255)),
                ('quantity_inspected', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('quantity_accepted', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('quantity_rejected', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('inspection_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_document_set', to='core.businessdocument')),
                ('goods_receipt', models.ForeignKey(blank=True, db_column='goods_receipt_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_goods_receipt_set', to='procurement.goodsreceipt')),
                ('inspector_user', models.ForeignKey(blank=True, db_column='inspector_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_inspector_user_set', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_product_set', to='master_data.product')),
                ('production_order', models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_production_order_set', to='manufacturing.productionorder')),
                ('work_order', models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_work_order_set', to='manufacturing.workorder')),
            ],
            options={
                'db_table': 'qa_inspection',
            },
        ),
        migrations.CreateModel(
            name='Nonconformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('disposition', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_nonconformance_document_set', to='core.businessdocument')),
                ('inspection', models.ForeignKey(blank=True, db_column='inspection_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_nonconformance_inspection_set', to='quality.inspection')),
            ],
            options={
                'db_table': 'qa_nonconformance',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_description', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('verification_result', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_correctiveaction_assigned_user_set', to=settings.AUTH_USER_MODEL)),
                ('nonconformance', models.ForeignKey(blank=True, db_column='nonconformance_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_correctiveaction_nonconformance_set', to='quality.nonconformance')),
            ],
            options={
                'db_table': 'qa_corrective_action',
            },
        ),
        migrations.CreateModel(
            name='QualityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(blank=True, default='', max_length=255)),
                ('inspection_stage', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_qualityplan_product_set', to='master_data.product')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_qualityplan_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'qa_quality_plan',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='quality_plan',
            field=models.ForeignKey(blank=True, db_column='quality_plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection_quality_plan_set', to='quality.qualityplan'),
        ),
        migrations.CreateModel(
            name='QualityPlanPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('parameter_name', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_type', models.CharField(blank=True, default='', max_length=255)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('quality_plan', models.ForeignKey(blank=True, db_column='quality_plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_qualityplanpoint_quality_plan_set', to='quality.qualityplan')),
            ],
            options={
                'db_table': 'qa_quality_plan_point',
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('text_value', models.CharField(blank=True, default='', max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('inspection', models.ForeignKey(blank=True, db_column='inspection_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspectionresult_inspection_set', to='quality.inspection')),
                ('plan_point', models.ForeignKey(blank=True, db_column='plan_point_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspectionresult_plan_point_set', to='quality.qualityplanpoint')),
            ],
            options={
                'db_table': 'qa_inspection_result',
            },
        ),
    ]
