# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_name', models.CharField(blank=True, default='', max_length=255)),
                ('board_type', models.CharField(blank=True, default='', max_length=255)),
                ('default_board', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_board',
            },
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('cost_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('resource_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('health_status', models.CharField(blank=True, default='', max_length=255)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'project_health_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_milestone',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_code', models.CharField(blank=True, default='', max_length=255)),
                ('requirement_type', models.CharField(blank=True, default='', max_length=255)),
                ('requirement_text', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
                ('verification_method', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_requirement',
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_start_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_end_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('allocated_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_resource_allocation',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('request_type', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
                ('approval_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_resource_request',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(blank=True, default='', max_length=255)),
                ('requested_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('requested_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('specification', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_resource_request_line',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_code', models.CharField(blank=True, default='', max_length=255)),
                ('risk_category', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('probability_score', models.IntegerField(blank=True, null=True)),
                ('impact_score', models.IntegerField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('mitigation_plan', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_risk',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_code', models.CharField(blank=True, default='', max_length=255)),
                ('task_name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
        migrations.CreateModel(
            name='TaskBoardPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_order', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('moved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_task_board_position',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(blank=True, default='', max_length=255)),
                ('lag_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_task_dependency',
            },
        ),
        migrations.CreateModel(
            name='TechnicalBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_number', models.CharField(blank=True, default='', max_length=255)),
                ('brief_title', models.CharField(blank=True, default='', max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('scope_summary', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_technical_brief',
            },
        ),
        migrations.CreateModel(
            name='TechnicalBriefVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('specification_text', models.TextField(blank=True, default='')),
                ('specification_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_technical_brief_version',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_timesheet',
            },
        ),
        migrations.CreateModel(
            name='WeightComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_code', models.CharField(blank=True, default='', max_length=255)),
                ('component_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('component_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'project_weight_component',
            },
        ),
        migrations.CreateModel(
            name='WeightIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_project_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weighted_project_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'project_weight_indicator',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_text', models.CharField(blank=True, default='', max_length=255)),
                ('expected_result', models.CharField(blank=True, default='', max_length=255)),
                ('actual_result', models.CharField(blank=True, default='', max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_acceptancecriteria_verified_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_acceptance_criteria',
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(blank=True, default='', max_length=255)),
                ('mapped_task_status', models.CharField(blank=True, default='', max_length=255)),
                ('position_order', models.IntegerField(blank=True, null=True)),
                ('wip_limit', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, db_column='board_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_boardcolumn_board_set', to='projects.board')),
            ],
            options={
                'db_table': 'project_board_column',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_element', models.CharField(blank=True, default='', max_length=255)),
                ('budget_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('budget_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_budgetline_account_set', to='finance.account')),
                ('cost_center', models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_budgetline_cost_center_set', to='master_data.costcenter')),
            ],
            options={
                'db_table': 'project_budget_line',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('schedule_impact_days', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_changerequest_document_set', to='core.businessdocument')),
            ],
            options={
                'db_table': 'project_change_request',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('usage_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_equipmentusage_asset_set', to='assets.asset')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_equipmentusage_employee_set', to='master_data.employee')),
                ('machine', models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_equipmentusage_machine_set', to='master_data.machine')),
            ],
            options={
                'db_table': 'project_equipment_usage',
            },
        ),
        migrations.CreateModel(
            name='HealthRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('health_dimension', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(blank=True, default='', max_length=255)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_healthrule_company_set', to='core.company')),
            ],
            options={
                'db_table': 'project_health_rule',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_issue_assigned_user_set', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_issue_document_set', to='core.businessdocument')),
            ],
            options={
                'db_table': 'project_issue',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('reserved_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('issued_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_materialrequirement_product_set', to='master_data.product')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_materialrequirement_warehouse_set', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'project_material_requirement',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_role', models.CharField(blank=True, default='', max_length=255)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_member_employee_set', to='master_data.employee')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_member_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_member',
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('planned_progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('earned_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('planned_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('progress_status', models.CharField(blank=True, default='', max_length=255)),
                ('work_order', models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_progresssnapshot_work_order_set', to='manufacturing.workorder')),
            ],
            options={
                'db_table': 'project_progress_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, default='', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_company_set', to='core.company')),
                ('cost_center', models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_cost_center_set', to='master_data.costcenter')),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_document_set', to='core.businessdocument')),
                ('project_manager', models.ForeignKey(blank=True, db_column='project_manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_project_manager_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_project',
            },
        ),
    ]
