# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0003_initial'),
        ('inventory', '0003_initial'),
        ('manufacturing', '0002_initial'),
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_project_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_progresssnapshot_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_milestone_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_member_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_materialrequirement_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_issue_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_healthsnapshot_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_equipmentusage_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_changerequest_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_budgetline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_board_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent_requirement',
            field=models.ForeignKey(blank=True, db_column='parent_requirement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_requirement_parent_requirement_set', to='projects.requirement'),
        ),
        migrations.AddField(
            model_name='acceptancecriteria',
            name='requirement',
            field=models.ForeignKey(blank=True, db_column='requirement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_acceptancecriteria_requirement_set', to='projects.requirement'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourceallocation_employee_set', to='master_data.employee'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='machine',
            field=models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourceallocation_machine_set', to='master_data.machine'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='stock_reservation',
            field=models.ForeignKey(blank=True, db_column='stock_reservation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourceallocation_stock_reservation_set', to='inventory.stockreservation'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequest_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequest_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequest_requested_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_employee_set', to='master_data.employee'),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='machine',
            field=models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_machine_set', to='master_data.machine'),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='resource_request',
            field=models.ForeignKey(blank=True, db_column='resource_request_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_resource_request_set', to='projects.resourcerequest'),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='resourcerequestline',
            name='work_center',
            field=models.ForeignKey(blank=True, db_column='work_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequestline_work_center_set', to='master_data.workcenter'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='resource_request_line',
            field=models.ForeignKey(blank=True, db_column='resource_request_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourceallocation_resource_request_line_set', to='projects.resourcerequestline'),
        ),
        migrations.AddField(
            model_name='risk',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_risk_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='risk',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_risk_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_risk_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, db_column='parent_task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_task_parent_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_task_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_task_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_center',
            field=models.ForeignKey(blank=True, db_column='work_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_task_work_center_set', to='master_data.workcenter'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_resourcerequest_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_materialrequirement_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_issue_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_equipmentusage_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='taskboardposition',
            name='board_column',
            field=models.ForeignKey(blank=True, db_column='board_column_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_taskboardposition_board_column_set', to='projects.boardcolumn'),
        ),
        migrations.AddField(
            model_name='taskboardposition',
            name='moved_by',
            field=models.ForeignKey(blank=True, db_column='moved_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_taskboardposition_moved_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskboardposition',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_taskboardposition_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='predecessor_task',
            field=models.ForeignKey(blank=True, db_column='predecessor_task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_taskdependency_predecessor_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='successor_task',
            field=models.ForeignKey(blank=True, db_column='successor_task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_taskdependency_successor_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='technicalbrief',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbrief_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='technicalbrief',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbrief_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalbrief',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbrief_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='technicalbrief',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbrief_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='technical_brief',
            field=models.ForeignKey(blank=True, db_column='technical_brief_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_requirement_technical_brief_set', to='projects.technicalbrief'),
        ),
        migrations.AddField(
            model_name='technicalbriefversion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbriefversion_created_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalbriefversion',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbriefversion_file_set', to='core.file'),
        ),
        migrations.AddField(
            model_name='technicalbriefversion',
            name='technical_brief',
            field=models.ForeignKey(blank=True, db_column='technical_brief_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_technicalbriefversion_technical_brief_set', to='projects.technicalbrief'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_timesheet_employee_set', to='master_data.employee'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_timesheet_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_timesheet_task_set', to='projects.task'),
        ),
        migrations.AddField(
            model_name='weightindicator',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_weightindicator_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='weightindicator',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_weightindicator_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='weightindicator',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_weightindicator_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='weightindicator',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_weightindicator_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='weightcomponent',
            name='project_weight_indicator',
            field=models.ForeignKey(blank=True, db_column='project_weight_indicator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_weightcomponent_project_weight_indicator_set', to='projects.weightindicator'),
        ),
    ]
