# Generated by Django 5.2.17 on 2026-08-12 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='health_status',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='lifecycle_status',
            field=models.CharField(blank=True, default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='source_type',
            field=models.CharField(blank=True, default='MANUAL', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('action', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='projects.project')),
            ],
            options={
                'db_table': 'project_lifecycle_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReadinessCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('blocking', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_checks', to='projects.project')),
            ],
            options={
                'db_table': 'project_readiness_check',
                'constraints': [models.UniqueConstraint(fields=('project', 'check_type'), name='uniq_project_readiness_type')],
            },
        ),
    ]
