# Generated by Django 5.2.17 on 2026-08-12 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_workflow'),
        ('projects', '0004_milestone_created_at_milestone_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectControlItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('RESOURCE', 'Resource'), ('RISK', 'Risk'), ('QUALITY', 'Quality'), ('DOCUMENT', 'Document')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='PLANNED', max_length=32)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_control_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_items', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_project_control_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_control_item',
                'ordering': ['item_type', 'target_date', 'created_at'],
                'indexes': [models.Index(fields=['project', 'item_type', 'status'], name='project_control_lookup')],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='OTHER', max_length=32)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_expenses', to='finance.billingdocument')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_project_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'expense_date'], name='project_expense_lookup')],
            },
        ),
    ]
