# Generated by Django 5.2.17 on 2026-08-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcontrolitem_projectexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
