# Generated by Django 5.2.17 on 2026-08-13 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('projects', '0007_membership_task_authorization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='analyzed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyzed_project_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_project_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='billing_adjustment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_decision_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='original_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_project_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='revised_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='status',
            field=models.CharField(blank=True, default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='alert_status',
            field=models.CharField(blank=True, default='NONE', max_length=32),
        ),
        migrations.AddField(
            model_name='issue',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='analyzed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyzed_project_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_project_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='source_department',
            field=models.CharField(blank=True, default='FACTORY', max_length=32),
        ),
        migrations.CreateModel(
            name='ChangeRequestMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_delta', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('applied_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.materialrequirement')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_changes', to='projects.changerequest')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'project_change_request_material',
            },
        ),
        migrations.CreateModel(
            name='IssueAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('equipment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('additional_labor_hours', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('status', models.CharField(blank=True, default='PLANNED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issue_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_issue_actions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.issue')),
            ],
            options={
                'db_table': 'project_issue_action',
            },
        ),
        migrations.CreateModel(
            name='ProjectDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_department', models.CharField(max_length=32)),
                ('dispatch_type', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, default='SENT', max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='projects.project')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_project_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_dispatch',
                'constraints': [models.UniqueConstraint(fields=('project', 'target_department', 'dispatch_type'), name='uniq_project_dispatch_target')],
            },
        ),
    ]
