# Generated by Django 5.2.17 on 2026-08-19 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_repair_sales_order_project_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeeklyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_progress', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actual_progress', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('previous_progress', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('progress_difference', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gap_to_target', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('BEHIND', 'Behind'), ('COMPLETED', 'Completed'), ('PLANNED', 'Planned')], default='ON_TRACK', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('issues', models.TextField(blank=True, default='')),
                ('achievements', models.TextField(blank=True, default='')),
                ('next_week_plan', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progresses', to='projects.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_weekly_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_weekly_progress',
                'ordering': ['week_number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'week_number'), name='uniq_project_weekly_progress')],
            },
        ),
    ]
