# Generated by Django 5.2.17 on 2026-08-19 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_project_weekly_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.CreateModel(
            name='ProjectFinancialSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('planned_budget', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('actual_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('expected_revenue', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('invoiced_revenue', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('realized_revenue', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('expected_gross_profit', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('actual_gross_profit', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('expected_margin_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('actual_margin_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('budget_variance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('revenue_variance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('cost_variance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('budget_utilization_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('revenue_achievement_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('financial_health_status', models.CharField(choices=[('PROFITABLE', 'Profitable'), ('AT_RISK', 'At Risk'), ('LOSS_MAKING', 'Loss Making'), ('BUDGET_OVERRUN', 'Budget Overrun'), ('BREAK_EVEN', 'Break Even')], default='PROFITABLE', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='projects.project')),
            ],
            options={
                'db_table': 'project_financial_snapshot',
                'ordering': ['-snapshot_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='proj_fin_snapshot_lookup')],
            },
        ),
    ]
