# Generated by Django 5.2.17 on 2026-08-21 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_contract_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMainTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=8)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('ON_HOLD', 'On Hold')], default='PLANNED', max_length=32)),
                ('is_progress_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_main_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_tasks', to='projects.project')),
            ],
            options={
                'db_table': 'project_main_task',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWeeklyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_description', models.TextField(blank=True, default='')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('ON_HOLD', 'On Hold')], default='PLANNED', max_length=32)),
                ('is_progress_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_weekly_tasks', to=settings.AUTH_USER_MODEL)),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='projects.projectmaintask')),
            ],
            options={
                'db_table': 'project_weekly_task',
                'ordering': ['week_number', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('REVIEW', 'In Review'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=32)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_daily_tasks', to=settings.AUTH_USER_MODEL)),
                ('weekly_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='projects.projectweeklytask')),
            ],
            options={
                'db_table': 'project_daily_task',
                'ordering': ['planned_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_level', models.CharField(choices=[('PROJECT', 'Project'), ('MAIN', 'Main Task'), ('WEEKLY', 'Weekly Task'), ('DAILY', 'Daily Task')], default='DAILY', max_length=16)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('task_title', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('field_name', models.CharField(blank=True, default='', max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activity_logs', to='projects.project')),
            ],
            options={
                'db_table': 'project_task_activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_by_pm', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.projectmaintask')),
            ],
            options={
                'db_table': 'project_task_assignment',
            },
        ),
        migrations.CreateModel(
            name='TaskTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='projects.projectdailytask')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_task_transfers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_task_transfers', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_task_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_task_transfer_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmaintask',
            index=models.Index(fields=['project', 'status'], name='proj_main_task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectweeklytask',
            index=models.Index(fields=['main_task', 'week_number'], name='proj_wk_task_week_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdailytask',
            index=models.Index(fields=['weekly_task', 'planned_date'], name='proj_dl_task_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdailytask',
            index=models.Index(fields=['owner', 'status'], name='proj_dl_task_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivitylog',
            index=models.Index(fields=['project', '-created_at'], name='task_act_log_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivitylog',
            index=models.Index(fields=['task_id', '-created_at'], name='task_act_log_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('main_task', 'assignee'), name='uniq_main_task_assignee'),
        ),
        migrations.AddIndex(
            model_name='tasktransferrequest',
            index=models.Index(fields=['status', 'created_at'], name='task_transfer_status_idx'),
        ),
    ]
