# Generated by Django 5.2.17 on 2026-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectmaintask_projectweeklytask_projectdailytask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdailytask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectdailytask',
            name='output_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectdailytask',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
