# Generated by Django 5.2.17 on 2026-08-21 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectdailytask_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEVMRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('week_number', models.IntegerField(default=1)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('schedule_variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('cost_performance_index', models.DecimalField(decimal_places=4, default=1.0, max_digits=7)),
                ('schedule_performance_index', models.DecimalField(decimal_places=4, default=1.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evm_records', to='projects.project')),
            ],
            options={
                'db_table': 'project_evm_record',
                'ordering': ['as_of_date'],
                'indexes': [models.Index(fields=['project', 'as_of_date'], name='proj_evm_date_idx')],
            },
        ),
    ]
