from django.urls import path

from .commands import (
    AlertEvaluateView,
    AssetDisposeView,
    AssetRunDepreciationView,
    BankStatementReconcileView,
    BillingDocumentPostView,
    BudgetCheckView,
    CorrectiveActionVerifyView,
    CRMSalesDashboardView,
    DocumentApproveView,
    DocumentCancelView,
    DocumentHistoryView,
    DocumentPostView,
    DocumentRejectView,
    DocumentReverseView,
    DocumentSubmitView,
    FinanceMainDashboardView,
    FiscalPeriodCloseView,
    FiscalPeriodReopenView,
    GoodsReceiptInspectView,
    InspectionCompleteView,
    JournalEntryPostView,
    KPIRecalculateView,
    NonconformanceDispositionView,
    PaymentAllocateView,
    ProductionOrderIssueMaterialsView,
    ProductionOrderReceiveOutputView,
    ProductionOrderReleaseView,
    ProjectCostsView,
    ProjectDashboardView,
    ProjectHealthView,
    ProjectProgressView,
    ProjectStartView,
    ProjectTaskMoveView,
    PurchaseOrderSendView,
    PurchaseOrderThreeWayMatchView,
    PurchaseRequisitionConvertToRFQView,
    QuotationConvertToOrderView,
    SalesDeliveryDispatchView,
    SalesOrderAllocateView,
    SalesOrderConfirmView,
    ServiceCaseResolveView,
    ShipmentEventsView,
    ShipmentProofOfDeliveryView,
    StockCountPostAdjustmentView,
    StockMoveCompleteView,
    StockReservationReleaseView,
    SupplierQuotationSelectView,
    TimesheetApproveView,
    WorkOrderCompleteView,
    WorkOrderStartView,
)


urlpatterns = [
    path("core/documents/<uuid:id>/submit/", DocumentSubmitView.as_view(), name="document-submit"),
    path("core/documents/<uuid:id>/approve/", DocumentApproveView.as_view(), name="document-approve"),
    path("core/documents/<uuid:id>/reject/", DocumentRejectView.as_view(), name="document-reject"),
    path("core/documents/<uuid:id>/post/", DocumentPostView.as_view(), name="document-post"),
    path("core/documents/<uuid:id>/cancel/", DocumentCancelView.as_view(), name="document-cancel"),
    path("core/documents/<uuid:id>/reverse/", DocumentReverseView.as_view(), name="document-reverse"),
    path("core/documents/<uuid:id>/history/", DocumentHistoryView.as_view(), name="document-history"),
    path("sales/quotations/<uuid:id>/convert-to-order/", QuotationConvertToOrderView.as_view(), name="quotation-convert-to-order"),
    path("sales/orders/<uuid:id>/confirm/", SalesOrderConfirmView.as_view(), name="sales-order-confirm"),
    path("sales/orders/<uuid:id>/allocate/", SalesOrderAllocateView.as_view(), name="sales-order-allocate"),
    path("sales/deliveries/<uuid:id>/dispatch/", SalesDeliveryDispatchView.as_view(), name="sales-delivery-dispatch"),
    path("projects/projects/<uuid:id>/start/", ProjectStartView.as_view(), name="project-start"),
    path("projects/projects/<uuid:id>/health/", ProjectHealthView.as_view(), name="project-health"),
    path("projects/projects/<uuid:id>/costs/", ProjectCostsView.as_view(), name="project-costs"),
    path("projects/projects/<uuid:id>/progress/", ProjectProgressView.as_view(), name="project-progress"),
    path("projects/tasks/<uuid:id>/move/", ProjectTaskMoveView.as_view(), name="project-task-move"),
    path("projects/timesheets/<uuid:id>/approve/", TimesheetApproveView.as_view(), name="timesheet-approve"),
    path("procurement/purchase-requisitions/<uuid:id>/convert-to-rfq/", PurchaseRequisitionConvertToRFQView.as_view(), name="purchase-requisition-convert-to-rfq"),
    path("procurement/supplier-quotations/<uuid:id>/select/", SupplierQuotationSelectView.as_view(), name="supplier-quotation-select"),
    path("procurement/purchase-orders/<uuid:id>/send/", PurchaseOrderSendView.as_view(), name="purchase-order-send"),
    path("procurement/goods-receipts/<uuid:id>/inspect/", GoodsReceiptInspectView.as_view(), name="goods-receipt-inspect"),
    path("procurement/purchase-orders/<uuid:id>/three-way-match/", PurchaseOrderThreeWayMatchView.as_view(), name="purchase-order-three-way-match"),
    path("inventory/stock-moves/<uuid:id>/complete/", StockMoveCompleteView.as_view(), name="stock-move-complete"),
    path("inventory/reservations/<uuid:id>/release/", StockReservationReleaseView.as_view(), name="stock-reservation-release"),
    path("inventory/stock-counts/<uuid:id>/post-adjustment/", StockCountPostAdjustmentView.as_view(), name="stock-count-post-adjustment"),
    path("manufacturing/production-orders/<uuid:id>/release/", ProductionOrderReleaseView.as_view(), name="production-order-release"),
    path("manufacturing/production-orders/<uuid:id>/issue-materials/", ProductionOrderIssueMaterialsView.as_view(), name="production-order-issue-materials"),
    path("manufacturing/work-orders/<uuid:id>/start/", WorkOrderStartView.as_view(), name="work-order-start"),
    path("manufacturing/work-orders/<uuid:id>/complete/", WorkOrderCompleteView.as_view(), name="work-order-complete"),
    path("manufacturing/production-orders/<uuid:id>/receive-output/", ProductionOrderReceiveOutputView.as_view(), name="production-order-receive-output"),
    path("quality/inspections/<uuid:id>/complete/", InspectionCompleteView.as_view(), name="inspection-complete"),
    path("quality/nonconformances/<uuid:id>/disposition/", NonconformanceDispositionView.as_view(), name="nonconformance-disposition"),
    path("quality/corrective-actions/<uuid:id>/verify/", CorrectiveActionVerifyView.as_view(), name="corrective-action-verify"),
    path("finance/journal-entries/<uuid:id>/post/", JournalEntryPostView.as_view(), name="journal-entry-post"),
    path("finance/billing-documents/<uuid:id>/post/", BillingDocumentPostView.as_view(), name="billing-document-post"),
    path("finance/payments/<uuid:id>/allocate/", PaymentAllocateView.as_view(), name="payment-allocate"),
    path("finance/bank-statements/<uuid:id>/reconcile/", BankStatementReconcileView.as_view(), name="bank-statement-reconcile"),
    path("finance/fiscal-periods/<uuid:id>/close/", FiscalPeriodCloseView.as_view(), name="fiscal-period-close"),
    path("finance/fiscal-periods/<uuid:id>/reopen/", FiscalPeriodReopenView.as_view(), name="fiscal-period-reopen"),
    path("finance/budgets/<uuid:id>/check/", BudgetCheckView.as_view(), name="budget-check"),
    path("assets/assets/<uuid:id>/run-depreciation/", AssetRunDepreciationView.as_view(), name="asset-run-depreciation"),
    path("assets/assets/<uuid:id>/dispose/", AssetDisposeView.as_view(), name="asset-dispose"),
    path("service/cases/<uuid:id>/resolve/", ServiceCaseResolveView.as_view(), name="service-case-resolve"),
    path("logistics/shipments/<uuid:id>/events/", ShipmentEventsView.as_view(), name="shipment-events"),
    path("logistics/shipments/<uuid:id>/proof-of-delivery/", ShipmentProofOfDeliveryView.as_view(), name="shipment-proof-of-delivery"),
    path("analytics/kpis/recalculate/", KPIRecalculateView.as_view(), name="kpi-recalculate"),
    path("analytics/alerts/evaluate/", AlertEvaluateView.as_view(), name="alert-evaluate"),
    path("reporting/finance-main-dashboard/", FinanceMainDashboardView.as_view(), name="finance-main-dashboard"),
    path("reporting/project-dashboard/<uuid:project_id>/", ProjectDashboardView.as_view(), name="project-dashboard"),
    path("reporting/crm-sales-dashboard/", CRMSalesDashboardView.as_view(), name="crm-sales-dashboard"),
]
