from django.urls import path

from apps.workflows.commands import (
    WorkflowTransitionsView,
    WorkflowExecuteTransitionView,
    WorkflowRegistryView,
)

from .commands import (
    AlertEvaluateView,
    AssetDisposeView,
    AssetRunDepreciationView,
    BankStatementReconcileView,
    BillingDocumentApproveView,
    BillingDocumentPostView,
    BillingDocumentRejectView,
    BillingDocumentVerifyView,
    BudgetCheckView,
    CorrectiveActionVerifyView,
    CostVarianceCalculateView,
    CreditFacilityCheckView,
    CRMSalesDashboardView,
    DocumentApproveView,
    DocumentCancelView,
    DocumentHistoryView,
    DocumentPostView,
    DocumentRejectView,
    DocumentReverseView,
    DocumentSubmitView,
    FinanceMainDashboardView,
    FinanceFlowStatusView,
    FinancialSnapshotCalculateView,
    FiscalPeriodCloseView,
    FiscalPeriodReopenView,
    GoodsReceiptInspectView,
    InspectionCompleteView,
    JournalEntryPostView,
    KPIRecalculateView,
    MaintenanceCompleteView,
    NonconformanceDispositionView,
    PaymentAllocateView,
    PaymentApproveView,
    PaymentBatchCreateView,
    PaymentExecuteView,
    PaymentSubmitView,
    OverheadAllocateView,
    ProductionOrderIssueMaterialsView,
    ProductionOrderReceiveOutputView,
    ProductionOrderReleaseView,
    ProjectCostsView,
    ProjectCloseView,
    ProjectDashboardView,
    ProjectHealthView,
    ProjectFinancialSummaryView,
    ProjectFinancialTargetView,
    PortfolioFinancialPerformanceView,
    ProjectFundingDrawView,
    ProjectProgressView,
    ProjectRecalculateProgressView,
    ProjectFlowStatusView,
    ProjectReserveMaterialsView,
    ProjectStartView,
    ProjectTaskMoveView,
    ProjectVerifyView,
    ProjectWeeklyMonitoringView,
    ProjectWeeklySnapshotView,
    ProjectWIPCalculateView,
    PurchaseOrderSendView,
    PurchaseOrderThreeWayMatchView,
    PurchaseRequisitionConvertToRFQView,
    QuotationConvertToOrderView,
    RecurringPaymentRunView,
    SalesDeliveryDispatchView,
    SalesOrderAllocateView,
    SalesOrderConfirmView,
    SalesOrderConvertToProjectView,
    ServiceCaseResolveView,
    ShipmentEventsView,
    ShipmentProofOfDeliveryView,
    StockCountPostAdjustmentView,
    StockMoveCompleteView,
    StockReservationReleaseView,
    SupplierQuotationSelectView,
    TimesheetApproveView,
    UnitCostCalculateView,
    WorkOrderCompleteView,
    WorkOrderStartView,
)


urlpatterns = [
    path("core/documents/<uuid:id>/submit/", DocumentSubmitView.as_view(), name="document-submit"),
    path("core/documents/<uuid:id>/approve/", DocumentApproveView.as_view(), name="document-approve"),
    path("core/documents/<uuid:id>/reject/", DocumentRejectView.as_view(), name="document-reject"),
    path("core/documents/<uuid:id>/post/", DocumentPostView.as_view(), name="document-post"),
    path("core/documents/<uuid:id>/cancel/", DocumentCancelView.as_view(), name="document-cancel"),
    path("core/documents/<uuid:id>/reverse/", DocumentReverseView.as_view(), name="document-reverse"),
    path("core/documents/<uuid:id>/history/", DocumentHistoryView.as_view(), name="document-history"),
    path("sales/quotations/<uuid:id>/convert-to-order/", QuotationConvertToOrderView.as_view(), name="quotation-convert-to-order"),
    path("sales/orders/<uuid:id>/confirm/", SalesOrderConfirmView.as_view(), name="sales-order-confirm"),
    path("sales/orders/<uuid:id>/allocate/", SalesOrderAllocateView.as_view(), name="sales-order-allocate"),
    path("sales/orders/<uuid:id>/convert-to-project/", SalesOrderConvertToProjectView.as_view(), name="sales-order-convert-to-project"),
    path("sales/deliveries/<uuid:id>/dispatch/", SalesDeliveryDispatchView.as_view(), name="sales-delivery-dispatch"),
    path("projects/projects/<uuid:id>/start/", ProjectStartView.as_view(), name="project-start"),
    path("projects/projects/<uuid:id>/close/", ProjectCloseView.as_view(), name="project-close"),
    path("projects/projects/<uuid:id>/flow-status/", ProjectFlowStatusView.as_view(), name="project-flow-status"),
    path("projects/projects/<uuid:id>/verify/", ProjectVerifyView.as_view(), name="project-verify"),
    path("projects/projects/<uuid:id>/reserve-materials/", ProjectReserveMaterialsView.as_view(), name="project-reserve-materials"),
    path("projects/projects/<uuid:id>/health/", ProjectHealthView.as_view(), name="project-health"),
    path("projects/projects/<uuid:id>/costs/", ProjectCostsView.as_view(), name="project-costs"),
    path("projects/projects/<uuid:id>/financial-summary/", ProjectFinancialSummaryView.as_view(), name="project-financial-summary"),
    path("projects/projects/<uuid:id>/financial-target/", ProjectFinancialTargetView.as_view(), name="project-financial-target"),
    path("projects/projects/<uuid:id>/progress/", ProjectProgressView.as_view(), name="project-progress"),
    path("projects/projects/<uuid:id>/recalculate-progress/", ProjectRecalculateProgressView.as_view(), name="project-recalculate-progress"),
    path("projects/projects/<uuid:id>/weekly-monitoring/", ProjectWeeklyMonitoringView.as_view(), name="project-weekly-monitoring"),
    path("projects/projects/<uuid:id>/weekly-snapshot/", ProjectWeeklySnapshotView.as_view(), name="project-weekly-snapshot"),
    path("reporting/portfolio-financial-performance/", PortfolioFinancialPerformanceView.as_view(), name="portfolio-financial-performance"),
    path("projects/tasks/<uuid:id>/move/", ProjectTaskMoveView.as_view(), name="project-task-move"),
    path("projects/timesheets/<uuid:id>/approve/", TimesheetApproveView.as_view(), name="timesheet-approve"),
    path("procurement/purchase-requisitions/<uuid:id>/convert-to-rfq/", PurchaseRequisitionConvertToRFQView.as_view(), name="purchase-requisition-convert-to-rfq"),
    path("procurement/supplier-quotations/<uuid:id>/select/", SupplierQuotationSelectView.as_view(), name="supplier-quotation-select"),
    path("procurement/purchase-orders/<uuid:id>/send/", PurchaseOrderSendView.as_view(), name="purchase-order-send"),
    path("procurement/goods-receipts/<uuid:id>/inspect/", GoodsReceiptInspectView.as_view(), name="goods-receipt-inspect"),
    path("procurement/purchase-orders/<uuid:id>/three-way-match/", PurchaseOrderThreeWayMatchView.as_view(), name="purchase-order-three-way-match"),
    path("inventory/stock-moves/<uuid:id>/complete/", StockMoveCompleteView.as_view(), name="stock-move-complete"),
    path("inventory/reservations/<uuid:id>/release/", StockReservationReleaseView.as_view(), name="stock-reservation-release"),
    path("inventory/stock-counts/<uuid:id>/post-adjustment/", StockCountPostAdjustmentView.as_view(), name="stock-count-post-adjustment"),
    path("manufacturing/production-orders/<uuid:id>/release/", ProductionOrderReleaseView.as_view(), name="production-order-release"),
    path("manufacturing/production-orders/<uuid:id>/issue-materials/", ProductionOrderIssueMaterialsView.as_view(), name="production-order-issue-materials"),
    path("manufacturing/work-orders/<uuid:id>/start/", WorkOrderStartView.as_view(), name="work-order-start"),
    path("manufacturing/work-orders/<uuid:id>/complete/", WorkOrderCompleteView.as_view(), name="work-order-complete"),
    path("manufacturing/production-orders/<uuid:id>/receive-output/", ProductionOrderReceiveOutputView.as_view(), name="production-order-receive-output"),
    path("quality/inspections/<uuid:id>/complete/", InspectionCompleteView.as_view(), name="inspection-complete"),
    path("quality/nonconformances/<uuid:id>/disposition/", NonconformanceDispositionView.as_view(), name="nonconformance-disposition"),
    path("quality/corrective-actions/<uuid:id>/verify/", CorrectiveActionVerifyView.as_view(), name="corrective-action-verify"),
    path("finance/journal-entries/<uuid:id>/post/", JournalEntryPostView.as_view(), name="journal-entry-post"),
    path("finance/billing-documents/<uuid:id>/post/", BillingDocumentPostView.as_view(), name="billing-document-post"),
    path("finance/billing-documents/<uuid:id>/verify/", BillingDocumentVerifyView.as_view(), name="billing-document-verify"),
    path("finance/billing-documents/<uuid:id>/approve/", BillingDocumentApproveView.as_view(), name="billing-document-approve"),
    path("finance/billing-documents/<uuid:id>/reject/", BillingDocumentRejectView.as_view(), name="billing-document-reject"),
    path("finance/payment-batches/create/", PaymentBatchCreateView.as_view(), name="payment-batch-create"),
    path("finance/payments/<uuid:id>/submit/", PaymentSubmitView.as_view(), name="payment-submit"),
    path("finance/payments/<uuid:id>/approve/", PaymentApproveView.as_view(), name="payment-approve"),
    path("finance/payments/<uuid:id>/execute/", PaymentExecuteView.as_view(), name="payment-execute"),
    path("finance/payments/<uuid:id>/allocate/", PaymentAllocateView.as_view(), name="payment-allocate"),
    path("finance/bank-statements/<uuid:id>/reconcile/", BankStatementReconcileView.as_view(), name="bank-statement-reconcile"),
    path("finance/fiscal-periods/<uuid:id>/close/", FiscalPeriodCloseView.as_view(), name="fiscal-period-close"),
    path("finance/fiscal-periods/<uuid:id>/reopen/", FiscalPeriodReopenView.as_view(), name="fiscal-period-reopen"),
    path("finance/budgets/<uuid:id>/check/", BudgetCheckView.as_view(), name="budget-check"),
    path("finance/flow-status/", FinanceFlowStatusView.as_view(), name="finance-flow-status"),
    path("finance/financial-snapshots/calculate/", FinancialSnapshotCalculateView.as_view(), name="financial-snapshot-calculate"),
    path("finance/production-orders/<uuid:id>/calculate-unit-cost/", UnitCostCalculateView.as_view(), name="unit-cost-calculate"),
    path("finance/projects/<uuid:id>/calculate-cost-variance/", CostVarianceCalculateView.as_view(), name="cost-variance-calculate"),
    path("finance/recurring-payment-rules/<uuid:id>/run/", RecurringPaymentRunView.as_view(), name="recurring-payment-run"),
    path("finance/credit-facilities/<uuid:id>/check/", CreditFacilityCheckView.as_view(), name="credit-facility-check"),
    path("finance/projects/<uuid:id>/calculate-wip/", ProjectWIPCalculateView.as_view(), name="project-wip-calculate"),
    path("finance/project-fundings/<uuid:id>/draw/", ProjectFundingDrawView.as_view(), name="project-funding-draw"),
    path("finance/overhead-rules/<uuid:id>/allocate/", OverheadAllocateView.as_view(), name="overhead-allocate"),
    path("assets/assets/<uuid:id>/run-depreciation/", AssetRunDepreciationView.as_view(), name="asset-run-depreciation"),
    path("assets/maintenances/<uuid:id>/complete/", MaintenanceCompleteView.as_view(), name="maintenance-complete"),
    path("assets/assets/<uuid:id>/dispose/", AssetDisposeView.as_view(), name="asset-dispose"),
    path("service/cases/<uuid:id>/resolve/", ServiceCaseResolveView.as_view(), name="service-case-resolve"),
    path("logistics/shipments/<uuid:id>/events/", ShipmentEventsView.as_view(), name="shipment-events"),
    path("logistics/shipments/<uuid:id>/proof-of-delivery/", ShipmentProofOfDeliveryView.as_view(), name="shipment-proof-of-delivery"),
    path("analytics/kpis/recalculate/", KPIRecalculateView.as_view(), name="kpi-recalculate"),
    path("analytics/alerts/evaluate/", AlertEvaluateView.as_view(), name="alert-evaluate"),
    path("reporting/finance-main-dashboard/", FinanceMainDashboardView.as_view(), name="finance-main-dashboard"),
    path("reporting/project-dashboard/<uuid:project_id>/", ProjectDashboardView.as_view(), name="project-dashboard"),
    path("reporting/crm-sales-dashboard/", CRMSalesDashboardView.as_view(), name="crm-sales-dashboard"),

    # -----------------------------------------------------------------------
    # Workflow Engine API
    # -----------------------------------------------------------------------
    path(
        "workflow/transitions/<str:module>/<uuid:document_id>/",
        WorkflowTransitionsView.as_view(),
        name="workflow-transitions",
    ),
    path(
        "workflow/execute/<str:module>/<uuid:document_id>/",
        WorkflowExecuteTransitionView.as_view(),
        name="workflow-execute",
    ),
    path(
        "workflow/registry/",
        WorkflowRegistryView.as_view(),
        name="workflow-registry",
    ),
]
