# Generated by Django 5.2.17 on 2026-08-19 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(db_index=True, max_length=100)),
                ('module_code', models.CharField(db_index=True, max_length=100)),
                ('document_id', models.CharField(db_index=True, help_text='UUID or PK of the document that was transitioned.', max_length=255)),
                ('from_status', models.CharField(max_length=100)),
                ('to_status', models.CharField(max_length=100)),
                ('triggered_by', models.CharField(help_text='UUID of the user who triggered this transition.', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Workflow Transition Log',
                'verbose_name_plural': 'Workflow Transition Logs',
                'db_table': 'workflow_transition_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantWorkflowConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(choices=[('SALES_ORDER', 'Sales Order'), ('SALES_QUOTATION', 'Sales Quotation'), ('PROJECT', 'Project Lifecycle'), ('PURCHASE_ORDER', 'Purchase Order'), ('INVOICE', 'Invoice / Billing'), ('PROCUREMENT_REQUEST', 'Procurement Request'), ('INVENTORY_MOVEMENT', 'Inventory Movement'), ('CRM_DEAL', 'CRM Deal')], help_text='The ERP module this workflow governs.', max_length=100)),
                ('workflow_class_path', models.CharField(help_text='Dotted Python path to the workflow class. Example: apps.workflows.tenants.arsalynk.sales_order.ArsalynkSalesWorkflow', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Optional config parameters passed to the workflow instance.')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_configs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Workflow Configuration',
                'verbose_name_plural': 'Tenant Workflow Configurations',
                'db_table': 'workflow_tenant_config',
                'unique_together': {('tenant', 'module_code')},
            },
        ),
    ]
