# Generated by Django 5.2.17 on 2026-08-05 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(blank=True, default='', max_length=255)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=255)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('planned_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('actual_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('shipment_status', models.CharField(blank=True, default='', max_length=255)),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipment_customer_party_set', to='master_data.party')),
                ('delivery', models.ForeignKey(blank=True, db_column='delivery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipment_delivery_set', to='sales.delivery')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipment_document_set', to='core.businessdocument')),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipment_sales_order_set', to='sales.order')),
            ],
            options={
                'db_table': 'logistics_shipment',
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('verification_status', models.CharField(blank=True, default='', max_length=255)),
                ('photo_file', models.ForeignKey(blank=True, db_column='photo_file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_proofofdelivery_photo_file_set', to='core.file')),
                ('received_by_party', models.ForeignKey(blank=True, db_column='received_by_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_proofofdelivery_received_by_party_set', to='master_data.party')),
                ('signature_file', models.ForeignKey(blank=True, db_column='signature_file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_proofofdelivery_signature_file_set', to='core.file')),
                ('shipment', models.ForeignKey(blank=True, db_column='shipment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_proofofdelivery_shipment_set', to='logistics.shipment')),
            ],
            options={
                'db_table': 'logistics_proof_of_delivery',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipped_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('delivery_line', models.ForeignKey(blank=True, db_column='delivery_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipmentline_delivery_line_set', to='sales.deliveryline')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipmentline_product_set', to='master_data.product')),
                ('shipment', models.ForeignKey(blank=True, db_column='shipment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipmentline_shipment_set', to='logistics.shipment')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_shipmentline_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'logistics_shipment_line',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(blank=True, default='', max_length=255)),
                ('event_description', models.CharField(blank=True, default='', max_length=255)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, default='', max_length=255)),
                ('shipment', models.ForeignKey(blank=True, db_column='shipment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_trackingevent_shipment_set', to='logistics.shipment')),
            ],
            options={
                'db_table': 'logistics_tracking_event',
            },
        ),
    ]
