    finally:
        server_cur.close()

    return exported


def validate_config():
    missing = []
    for env_name, key in [
        ("PGDATABASE", "dbname"),
        ("PGUSER", "user"),
        ("PGPASSWORD", "password"),
    ]:
        if not PG_CONFIG[key]:
            missing.append(env_name)

    if missing:
        raise RuntimeError(
            "Environment PostgreSQL belum lengkap. Isi: "
            + ", ".join(missing)
        )


def main():
    validate_config()

    print("=" * 70)
    print("PostgreSQL -> MySQL SQL Data Export")
    print("=" * 70)
    print(f"Source : {PG_CONFIG['host']}:{PG_CONFIG['port']}/{PG_CONFIG['dbname']}")
    print(f"Schema : {PG_SCHEMA}")
    print(f"Output : {OUTPUT_SQL.resolve()}")
    print(f"Tables : {len(TABLES)}")
    print(f"Upsert : {MYSQL_UPSERT}")
    print("=" * 70)

    conn = None
    total_exported = 0
    failed_tables = []

    try:
        conn = psycopg2.connect(**PG_CONFIG)
        conn.set_session(readonly=True, autocommit=False)

        with OUTPUT_SQL.open("w", encoding="utf-8", newline="\n") as out:
            out.write("-- PostgreSQL data export for MySQL\n")
            out.write("-- Generated by export_postgres_to_mysql_sql.py\n")
            out.write("SET NAMES utf8mb4;\n")
            out.write("SET CHARACTER SET utf8mb4;\n")
            out.write("SET FOREIGN_KEY_CHECKS=0;\n")
            out.write("SET UNIQUE_CHECKS=0;\n")
            out.write("SET AUTOCOMMIT=0;\n")
            out.write("START TRANSACTION;\n")

            for index, table_name in enumerate(TABLES, start=1):
                print(f"\n[{index}/{len(TABLES)}] {table_name}")

                try:
                    count = export_table(conn, out, table_name)
                    total_exported += count

                    # Server-side cursor membuka transaksi; rollback aman
                    # karena koneksi readonly dan membebaskan snapshot.
                    conn.rollback()

                except Exception as exc:
                    failed_tables.append((table_name, str(exc)))
                    print(f"[ERROR] {table_name}: {exc}", file=sys.stderr)
                    out.write(
                        f"\n-- ERROR exporting {table_name}: "
                        f"{str(exc).replace(chr(10), ' ')}\n"
                    )
                    conn.rollback()

            out.write("\nCOMMIT;\n")
            out.write("SET UNIQUE_CHECKS=1;\n")
            out.write("SET FOREIGN_KEY_CHECKS=1;\n")

            if failed_tables:
                out.write("\n-- Failed tables:\n")
                for table_name, error in failed_tables:
                    safe_error = error.replace("\n", " ")
                    out.write(f"-- {table_name}: {safe_error}\n")

        print("\n" + "=" * 70)
        print(f"SELESAI. Total row diexport: {total_exported}")
        print(f"File SQL: {OUTPUT_SQL.resolve()}")

        if failed_tables:
            print(f"WARNING: {len(failed_tables)} tabel gagal:")
            for table_name, error in failed_tables:
                print(f" - {table_name}: {error}")
            sys.exit(2)

        print("Semua tabel berhasil diproses.")

    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    main()
