# Generated by Django 5.2.17 on 2026-08-05 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_code', models.CharField(blank=True, default='', max_length=255)),
                ('phase_name', models.CharField(blank=True, default='', max_length=255)),
                ('phase_order', models.IntegerField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'implementation_phase',
            },
        ),
        migrations.CreateModel(
            name='PhaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('item_type', models.CharField(blank=True, default='', max_length=255)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('phase', models.ForeignKey(blank=True, db_column='phase_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_phaseitem_phase_set', to='implementation.phase')),
            ],
            options={
                'db_table': 'implementation_phase_item',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('release_name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('release_status', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_release_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'implementation_release',
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='release',
            field=models.ForeignKey(blank=True, db_column='release_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_phase_release_set', to='implementation.release'),
        ),
        migrations.CreateModel(
            name='GTMMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(blank=True, default='', max_length=255)),
                ('milestone_name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('release', models.ForeignKey(blank=True, db_column='release_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_gtmmilestone_release_set', to='implementation.release')),
            ],
            options={
                'db_table': 'implementation_gtm_milestone',
            },
        ),
        migrations.CreateModel(
            name='TestCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_scope', models.CharField(blank=True, default='', max_length=255)),
                ('test_type', models.CharField(blank=True, default='', max_length=255)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('passed_count', models.IntegerField(blank=True, null=True)),
                ('failed_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('phase', models.ForeignKey(blank=True, db_column='phase_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_testcycle_phase_set', to='implementation.phase')),
                ('release', models.ForeignKey(blank=True, db_column='release_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_testcycle_release_set', to='implementation.release')),
            ],
            options={
                'db_table': 'implementation_test_cycle',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('workflow_name', models.CharField(blank=True, default='', max_length=255)),
                ('methodology', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('release', models.ForeignKey(blank=True, db_column='release_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workflow_release_set', to='implementation.release')),
            ],
            options={
                'db_table': 'implementation_workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_code', models.CharField(blank=True, default='', max_length=255)),
                ('stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('stage_order', models.IntegerField(blank=True, null=True)),
                ('stage_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.ForeignKey(blank=True, db_column='workflow_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workflowstage_workflow_set', to='implementation.workflow')),
            ],
            options={
                'db_table': 'implementation_workflow_stage',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('work_item_type', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workitem_assigned_user_set', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, db_column='phase_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workitem_phase_set', to='implementation.phase')),
                ('release', models.ForeignKey(blank=True, db_column='release_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workitem_release_set', to='implementation.release')),
                ('workflow_stage', models.ForeignKey(blank=True, db_column='workflow_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementation_workitem_workflow_stage_set', to='implementation.workflowstage')),
            ],
            options={
                'db_table': 'implementation_work_item',
            },
        ),
    ]
