from rest_framework.routers import DefaultRouter
from .viewsets import FiscalYearViewSet, FiscalPeriodViewSet, AccountViewSet, JournalViewSet, JournalEntryViewSet, JournalLineViewSet, BillingDocumentViewSet, BillingDocumentLineViewSet, ARAPScheduleViewSet, PaymentViewSet, PaymentAllocationViewSet, BankAccountViewSet, BankStatementViewSet, BankStatementLineViewSet, BankReconciliationViewSet, TaxTransactionViewSet, BudgetViewSet, BudgetLineViewSet, PeriodClosingViewSet, FinancialSnapshotViewSet, UnitCostSnapshotViewSet, RecurringPaymentRuleViewSet, RecurringPaymentRunViewSet, CreditFacilityViewSet, ProjectWIPSnapshotViewSet, ProjectFundingViewSet, ProjectFundingTransactionViewSet, CostBaselineViewSet, CostBaselineLineViewSet, CostVarianceViewSet, OverheadRuleViewSet, OverheadAllocationViewSet, ProjectCostSnapshotViewSet, ProjectCostEntryViewSet, BillingProposalViewSet, InvoiceVarianceCaseViewSet

app_name = "finance"
router = DefaultRouter()
router.register(r"fiscal-years", FiscalYearViewSet, basename="fiscal-year")
router.register(r"fiscal-periods", FiscalPeriodViewSet, basename="fiscal-period")
router.register(r"accounts", AccountViewSet, basename="account")
router.register(r"journals", JournalViewSet, basename="journal")
router.register(r"journal-entries", JournalEntryViewSet, basename="journal-entry")
router.register(r"journal-lines", JournalLineViewSet, basename="journal-line")
router.register(r"billing-documents", BillingDocumentViewSet, basename="billing-document")
router.register(r"billing-document-lines", BillingDocumentLineViewSet, basename="billing-document-line")
router.register(r"arap-schedules", ARAPScheduleViewSet, basename="arap-schedule")
router.register(r"payments", PaymentViewSet, basename="payment")
router.register(r"payment-allocations", PaymentAllocationViewSet, basename="payment-allocation")
router.register(r"bank-accounts", BankAccountViewSet, basename="bank-account")
router.register(r"bank-statements", BankStatementViewSet, basename="bank-statement")
router.register(r"bank-statement-lines", BankStatementLineViewSet, basename="bank-statement-line")
router.register(r"bank-reconciliations", BankReconciliationViewSet, basename="bank-reconciliation")
router.register(r"tax-transactions", TaxTransactionViewSet, basename="tax-transaction")
router.register(r"budgets", BudgetViewSet, basename="budget")
router.register(r"budget-lines", BudgetLineViewSet, basename="budget-line")
router.register(r"period-closings", PeriodClosingViewSet, basename="period-closing")
router.register(r"financial-snapshots", FinancialSnapshotViewSet, basename="financial-snapshot")
router.register(r"unit-cost-snapshots", UnitCostSnapshotViewSet, basename="unit-cost-snapshot")
router.register(r"recurring-payment-rules", RecurringPaymentRuleViewSet, basename="recurring-payment-rule")
router.register(r"recurring-payment-runs", RecurringPaymentRunViewSet, basename="recurring-payment-run")
router.register(r"credit-facilities", CreditFacilityViewSet, basename="credit-facility")
router.register(r"project-wip-snapshots", ProjectWIPSnapshotViewSet, basename="project-wip-snapshot")
router.register(r"project-fundings", ProjectFundingViewSet, basename="project-funding")
router.register(r"project-funding-transactions", ProjectFundingTransactionViewSet, basename="project-funding-transaction")
router.register(r"cost-baselines", CostBaselineViewSet, basename="cost-baseline")
router.register(r"cost-baseline-lines", CostBaselineLineViewSet, basename="cost-baseline-line")
router.register(r"cost-variances", CostVarianceViewSet, basename="cost-variance")
router.register(r"overhead-rules", OverheadRuleViewSet, basename="overhead-rule")
router.register(r"overhead-allocations", OverheadAllocationViewSet, basename="overhead-allocation")
router.register(r"project-cost-snapshots", ProjectCostSnapshotViewSet, basename="project-cost-snapshot")
router.register(r"project-cost-entries", ProjectCostEntryViewSet, basename="project-cost-entry")
router.register(r"billing-proposals", BillingProposalViewSet, basename="billing-proposal")
router.register(r"invoice-variance-cases", InvoiceVarianceCaseViewSet, basename="invoice-variance-case")

urlpatterns = router.urls
