# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('currency_name', models.CharField(blank=True, default='', max_length=255)),
                ('symbol', models.CharField(blank=True, default='', max_length=255)),
                ('decimal_places', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_currency',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_center_code', models.CharField(blank=True, default='', max_length=255)),
                ('cost_center_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_costcenter_company_set', to='core.company')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_costcenter_parent_set', to='master_data.costcenter')),
            ],
            options={
                'db_table': 'master_cost_center',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(blank=True, default='', max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_department_company_set', to='core.company')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_department_parent_set', to='master_data.department')),
            ],
            options={
                'db_table': 'master_department',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rate_source', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_exchangerate_company_set', to='core.company')),
                ('from_currency', models.ForeignKey(blank=True, db_column='from_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_exchangerate_from_currency_set', to='master_data.currency')),
                ('to_currency', models.ForeignKey(blank=True, db_column='to_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_exchangerate_to_currency_set', to='master_data.currency')),
            ],
            options={
                'db_table': 'master_exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_code', models.CharField(blank=True, default='', max_length=255)),
                ('party_type', models.CharField(blank=True, default='', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_number', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('default_currency', models.ForeignKey(blank=True, db_column='default_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_party_default_currency_set', to='master_data.currency')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_party_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'master_party',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(blank=True, default='', max_length=255)),
                ('employment_status', models.CharField(blank=True, default='', max_length=255)),
                ('standard_hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_employee_department_set', to='master_data.department')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_employee_tenant_set', to='core.tenant')),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_employee_party_set', to='master_data.party')),
            ],
            options={
                'db_table': 'master_employee',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('primary_contact', models.BooleanField(default=False)),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_contact_party_set', to='master_data.party')),
            ],
            options={
                'db_table': 'master_contact',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(blank=True, default='', max_length=255)),
                ('address_line', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('province', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=255)),
                ('primary_address', models.BooleanField(default=False)),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_address_party_set', to='master_data.party')),
            ],
            options={
                'db_table': 'master_address',
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_partyrole_party_set', to='master_data.party')),
            ],
            options={
                'db_table': 'master_party_role',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_code', models.CharField(blank=True, default='', max_length=255)),
                ('term_name', models.CharField(blank=True, default='', max_length=255)),
                ('due_days', models.IntegerField(blank=True, null=True)),
                ('early_discount_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('early_discount_days', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_paymentterm_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'master_payment_term',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, default='', max_length=255)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('credit_hold', models.BooleanField(default=False)),
                ('price_list_id', models.UUIDField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, default='', max_length=255)),
                ('receivable_account', models.ForeignKey(blank=True, db_column='receivable_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_customerprofile_receivable_account_set', to='finance.account')),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_customerprofile_party_set', to='master_data.party')),
                ('payment_term', models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_customerprofile_payment_term_set', to='master_data.paymentterm')),
            ],
            options={
                'db_table': 'master_customer_profile',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_code', models.CharField(blank=True, default='', max_length=255)),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_productcategory_parent_set', to='master_data.productcategory')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_productcategory_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'master_product_category',
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=255)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('approved_supplier', models.BooleanField(default=False)),
                ('party', models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_supplierprofile_party_set', to='master_data.party')),
                ('payable_account', models.ForeignKey(blank=True, db_column='payable_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_supplierprofile_payable_account_set', to='finance.account')),
                ('payment_term', models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_supplierprofile_payment_term_set', to='master_data.paymentterm')),
            ],
            options={
                'db_table': 'master_supplier_profile',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_code', models.CharField(blank=True, default='', max_length=255)),
                ('tax_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_type', models.CharField(blank=True, default='', max_length=255)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('input_account', models.ForeignKey(blank=True, db_column='input_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_taxcode_input_account_set', to='finance.account')),
                ('output_account', models.ForeignKey(blank=True, db_column='output_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_taxcode_output_account_set', to='finance.account')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_taxcode_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'master_tax_code',
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uom_code', models.CharField(blank=True, default='', max_length=255)),
                ('uom_name', models.CharField(blank=True, default='', max_length=255)),
                ('dimension_type', models.CharField(blank=True, default='', max_length=255)),
                ('base_uom', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_uom_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'master_uom',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('costing_method', models.CharField(blank=True, default='', max_length=255)),
                ('stock_item', models.BooleanField(default=False)),
                ('purchase_item', models.BooleanField(default=False)),
                ('sales_item', models.BooleanField(default=False)),
                ('manufactured_item', models.BooleanField(default=False)),
                ('lot_controlled', models.BooleanField(default=False)),
                ('serial_controlled', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_product_tenant_set', to='core.tenant')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_product_category_set', to='master_data.productcategory')),
                ('base_uom', models.ForeignKey(blank=True, db_column='base_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_product_base_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'master_product',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=255)),
                ('warehouse_name', models.CharField(blank=True, default='', max_length=255)),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_warehouse_company_set', to='core.company')),
            ],
            options={
                'db_table': 'master_warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(blank=True, default='', max_length=255)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('location_type', models.CharField(blank=True, default='', max_length=255)),
                ('quality_hold', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_warehouselocation_parent_set', to='master_data.warehouselocation')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_warehouselocation_warehouse_set', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'master_warehouse_location',
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_center_code', models.CharField(blank=True, default='', max_length=255)),
                ('work_center_name', models.CharField(blank=True, default='', max_length=255)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('capacity_per_day', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_workcenter_company_set', to='core.company')),
            ],
            options={
                'db_table': 'master_work_center',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_code', models.CharField(blank=True, default='', max_length=255)),
                ('machine_name', models.CharField(blank=True, default='', max_length=255)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_machine_asset_set', to='assets.asset')),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_machine_company_set', to='core.company')),
                ('work_center', models.ForeignKey(blank=True, db_column='work_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_data_machine_work_center_set', to='master_data.workcenter')),
            ],
            options={
                'db_table': 'master_machine',
            },
        ),
    ]
