# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(blank=True, default='', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_number', models.CharField(blank=True, default='', max_length=255)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_company',
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('visible_to_customer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_document_attachment',
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_document_link',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(blank=True, default='', max_length=255)),
                ('signature_status', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reference', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_document_signature',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('template_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(blank=True, default='', max_length=255)),
                ('output_format', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_document_template',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(blank=True, default='', max_length=255)),
                ('source_path', models.CharField(blank=True, default='', max_length=255)),
                ('field_type', models.CharField(blank=True, default='', max_length=255)),
                ('format_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_document_template_field',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('header_markup', models.TextField(blank=True, default='')),
                ('body_markup', models.TextField(blank=True, default='')),
                ('footer_markup', models.TextField(blank=True, default='')),
                ('style_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_document_template_version',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_file',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_number', models.IntegerField(blank=True, null=True)),
                ('generation_status', models.CharField(blank=True, default='', max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_generated_document',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_notification_recipient',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_code', models.CharField(blank=True, default='', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_organization',
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('action_name', models.CharField(blank=True, default='', max_length=255)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('route_path', models.CharField(blank=True, default='', max_length=255)),
                ('default_payload', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_quick_action',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.CharField(blank=True, default='', max_length=255)),
                ('decision', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_workflow_approval',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_code', models.CharField(blank=True, default='', max_length=255)),
                ('current_state', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, default='', max_length=255)),
                ('document_number', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_approved_by_set', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_column='posted_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_posted_by_set', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_reversal_of_set', to='core.businessdocument')),
            ],
            options={
                'db_table': 'core_business_document',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_auditevent_user_set', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_auditevent_document_set', to='core.businessdocument')),
            ],
            options={
                'db_table': 'core_audit_event',
            },
        ),
    ]
