# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('analytics', '0002_initial'),
        ('core', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(blank=True, db_column='base_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_company_base_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_auditevent_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentattachment_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='documentlink',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentlink_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='documentlink',
            name='target_document',
            field=models.ForeignKey(blank=True, db_column='target_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentlink_target_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer_party',
            field=models.ForeignKey(blank=True, db_column='signer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentsignature_signer_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer_user',
            field=models.ForeignKey(blank=True, db_column='signer_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentsignature_signer_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documenttemplate_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='documenttemplateversion',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documenttemplateversion_template_set', to='core.documenttemplate'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='template_version',
            field=models.ForeignKey(blank=True, db_column='template_version_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documenttemplatefield_template_version_set', to='core.documenttemplateversion'),
        ),
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_file_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_file_uploaded_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentattachment_file_set', to='core.file'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='business_document',
            field=models.ForeignKey(blank=True, db_column='business_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_generateddocument_business_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_generateddocument_file_set', to='core.file'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='generated_by',
            field=models.ForeignKey(blank=True, db_column='generated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_generateddocument_generated_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='template_version',
            field=models.ForeignKey(blank=True, db_column='template_version_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_generateddocument_template_version_set', to='core.documenttemplateversion'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='generated_document',
            field=models.ForeignKey(blank=True, db_column='generated_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documentsignature_generated_document_set', to='core.generateddocument'),
        ),
        migrations.AddField(
            model_name='notification',
            name='alert_event',
            field=models.ForeignKey(blank=True, db_column='alert_event_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notification_alert_event_set', to='analytics.alertevent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notification_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notification_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(blank=True, db_column='notification_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notificationrecipient_notification_set', to='core.notification'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='recipient_role',
            field=models.ForeignKey(blank=True, db_column='recipient_role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notificationrecipient_recipient_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='recipient_user',
            field=models.ForeignKey(blank=True, db_column='recipient_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notificationrecipient_recipient_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_organization_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_organization_parent_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='quickaction',
            name='required_permission',
            field=models.ForeignKey(blank=True, db_column='required_permission_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_quickaction_required_permission_set', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='quickaction',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_quickaction_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_organization_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_notification_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='file',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_file_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_documenttemplate_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_company_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_businessdocument_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_auditevent_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='approver_user',
            field=models.ForeignKey(blank=True, db_column='approver_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_workflowapproval_approver_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_workflowinstance_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, db_column='workflow_instance_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_workflowapproval_workflow_instance_set', to='core.workflowinstance'),
        ),
    ]
