# Generated by Django 5.2.17 on 2026-08-26 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('REVIEW_ASKED', 'Asking for a review'), ('DOC_SENT', 'Sent a document'), ('REPORT_APPROVED', 'Report Approved'), ('REPORT_UPLOADED', 'Uploaded report'), ('GENERIC_ACTION', 'Action')], max_length=32)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=512)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_feeds', to='core.company')),
            ],
            options={
                'db_table': 'core_activity_feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('DOCUMENT', 'Document Sent'), ('ACCESS_REQUEST', 'Access Request'), ('STATUS_UPDATE', 'Status Update'), ('AUTH', 'Authentication')], default='DOCUMENT', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_app_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=True)),
                ('custom_status', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_team_contact',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserRecentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('PROJECT', 'Project'), ('ORDER', 'Order'), ('RESOURCE', 'Resource'), ('REPORT', 'Report')], max_length=32)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('target_url', models.CharField(max_length=512)),
                ('last_accessed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_recent_item',
                'ordering': ['-last_accessed_at'],
                'indexes': [models.Index(fields=['user', '-last_accessed_at'], name='core_user_r_user_id_42fdf4_idx')],
            },
        ),
    ]
