# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'mfg_labor_log',
            },
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('run_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('setup_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('machine_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'mfg_machine_log',
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('reserved_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('issued_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('returned_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'mfg_production_material',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('completed_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('scrapped_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('material_status', models.CharField(blank=True, default='', max_length=255)),
                ('quality_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mfg_production_order',
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('produced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mfg_production_output',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routing_code', models.CharField(blank=True, default='', max_length=255)),
                ('routing_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mfg_routing',
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('operation_name', models.CharField(blank=True, default='', max_length=255)),
                ('setup_minutes', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('run_minutes_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'mfg_routing_operation',
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrap_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('scrap_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=255)),
                ('disposition', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mfg_scrap',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('completed_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rejected_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mfg_work_order',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_code', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bom_product_set', to='master_data.product')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bom_tenant_set', to='core.tenant')),
            ],
            options={
                'db_table': 'mfg_bom',
            },
        ),
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('bom', models.ForeignKey(blank=True, db_column='bom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomversion_bom_set', to='manufacturing.bom')),
                ('output_uom', models.ForeignKey(blank=True, db_column='output_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomversion_output_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'mfg_bom_version',
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('scrap_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('issue_method', models.CharField(blank=True, default='', max_length=255)),
                ('component_product', models.ForeignKey(blank=True, db_column='component_product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomline_component_product_set', to='master_data.product')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomline_uom_set', to='master_data.uom')),
                ('bom_version', models.ForeignKey(blank=True, db_column='bom_version_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomline_bom_version_set', to='manufacturing.bomversion')),
            ],
            options={
                'db_table': 'mfg_bom_line',
            },
        ),
        migrations.CreateModel(
            name='CostLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_element', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('posting_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_company_set', to='core.company')),
                ('journal_line', models.ForeignKey(blank=True, db_column='journal_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_journal_line_set', to='finance.journalline')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_product_set', to='master_data.product')),
            ],
            options={
                'db_table': 'mfg_cost_ledger_entry',
            },
        ),
    ]
