# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0003_initial'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costledgerentry',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_reversal_of_set', to='manufacturing.costledgerentry'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='stock_ledger_entry',
            field=models.ForeignKey(blank=True, db_column='stock_ledger_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_stock_ledger_entry_set', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='laborlog',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_laborlog_employee_set', to='master_data.employee'),
        ),
        migrations.AddField(
            model_name='laborlog',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_laborlog_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='machinelog',
            name='machine',
            field=models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_machinelog_machine_set', to='master_data.machine'),
        ),
        migrations.AddField(
            model_name='machinelog',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_machinelog_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionmaterial_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionmaterial_warehouse_set', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='bom_version',
            field=models.ForeignKey(blank=True, db_column='bom_version_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_bom_version_set', to='manufacturing.bomversion'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, db_column='sales_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_sales_order_line_set', to='sales.orderline'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_warehouse_set', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionmaterial_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='destination_location',
            field=models.ForeignKey(blank=True, db_column='destination_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionoutput_destination_location_set', to='master_data.warehouselocation'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionoutput_lot_set', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionoutput_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionoutput_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='routing',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_routing_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='routing',
            field=models.ForeignKey(blank=True, db_column='routing_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_productionorder_routing_set', to='manufacturing.routing'),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='routing',
            field=models.ForeignKey(blank=True, db_column='routing_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_routingoperation_routing_set', to='manufacturing.routing'),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='work_center',
            field=models.ForeignKey(blank=True, db_column='work_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_routingoperation_work_center_set', to='master_data.workcenter'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='operation',
            field=models.ForeignKey(blank=True, db_column='operation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bomline_operation_set', to='manufacturing.routingoperation'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_scrap_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_scrap_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_workorder_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='machine',
            field=models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_workorder_machine_set', to='master_data.machine'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_workorder_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='routing_operation',
            field=models.ForeignKey(blank=True, db_column='routing_operation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_workorder_routing_operation_set', to='manufacturing.routingoperation'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_center',
            field=models.ForeignKey(blank=True, db_column='work_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_workorder_work_center_set', to='master_data.workcenter'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_scrap_work_order_set', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='machinelog',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_machinelog_work_order_set', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='laborlog',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_laborlog_work_order_set', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_costledgerentry_work_order_set', to='manufacturing.workorder'),
        ),
    ]
