# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        ('inventory', '0002_initial'),
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_assigned_user_set', to=settings.AUTH_USER_MODEL)),
                ('billing_document', models.ForeignKey(blank=True, db_column='billing_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_billing_document_set', to='finance.billingdocument')),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_contact_set', to='master_data.contact')),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_document_set', to='core.businessdocument')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_product_set', to='master_data.product')),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_sales_order_set', to='sales.order')),
                ('serial_number', models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_case_serial_number_set', to='inventory.serialnumber')),
            ],
            options={
                'db_table': 'service_case',
            },
        ),
        migrations.CreateModel(
            name='CaseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(blank=True, default='', max_length=255)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('decision', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(blank=True, db_column='approver_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_caseapproval_approver_user_set', to=settings.AUTH_USER_MODEL)),
                ('service_case', models.ForeignKey(blank=True, db_column='service_case_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_caseapproval_service_case_set', to='service.case')),
            ],
            options={
                'db_table': 'service_case_approval',
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, default='', max_length=255)),
                ('message_text', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sender_user', models.ForeignKey(blank=True, db_column='sender_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_casemessage_sender_user_set', to=settings.AUTH_USER_MODEL)),
                ('service_case', models.ForeignKey(blank=True, db_column='service_case_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_casemessage_service_case_set', to='service.case')),
            ],
            options={
                'db_table': 'service_case_message',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_notes', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('credit_note', models.ForeignKey(blank=True, db_column='credit_note_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_resolution_credit_note_set', to='finance.billingdocument')),
                ('replacement_delivery', models.ForeignKey(blank=True, db_column='replacement_delivery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_resolution_replacement_delivery_set', to='sales.delivery')),
                ('service_case', models.ForeignKey(blank=True, db_column='service_case_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_resolution_service_case_set', to='service.case')),
            ],
            options={
                'db_table': 'service_resolution',
            },
        ),
    ]
