# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAPSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_ar_ap_schedule',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_bank_account',
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('match_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_bank_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_bank_statement',
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_bank_statement_line',
            },
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_type', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('payment_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_billing_document',
            },
        ),
        migrations.CreateModel(
            name='BillingDocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_billing_document_line',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_name', models.CharField(blank=True, default='', max_length=255)),
                ('budget_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_budget',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_budget_line',
            },
        ),
        migrations.CreateModel(
            name='CostBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_version', models.IntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('total_ideal_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_cost_baseline',
            },
        ),
        migrations.CreateModel(
            name='CostBaselineLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_element', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ideal_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_cost_baseline_line',
            },
        ),
        migrations.CreateModel(
            name='CostVariance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ideal_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_cost_variance',
            },
        ),
        migrations.CreateModel(
            name='CreditFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_type', models.CharField(blank=True, default='', max_length=255)),
                ('facility_number', models.CharField(blank=True, default='', max_length=255)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('utilized_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_credit_facility',
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('revenue_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('profit_loss_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('operating_cashflow', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('investing_cashflow', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('financing_cashflow', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('snapshot_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_financial_snapshot',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_fiscal_period',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_fiscal_year',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_code', models.CharField(blank=True, default='', max_length=255)),
                ('journal_name', models.CharField(blank=True, default='', max_length=255)),
                ('journal_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_journal',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(blank=True, default='', max_length=255)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_base', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('credit_base', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_journal_line',
            },
        ),
        migrations.CreateModel(
            name='OverheadAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basis_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('allocated_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_overhead_allocation',
            },
        ),
        migrations.CreateModel(
            name='OverheadRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('allocation_basis', models.CharField(blank=True, default='', max_length=255)),
                ('rate_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_overhead_rule',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=255)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('write_off_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('exchange_difference', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_payment_allocation',
            },
        ),
        migrations.CreateModel(
            name='PeriodClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_period_closing',
            },
        ),
        migrations.CreateModel(
            name='ProjectCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('committed_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('overhead_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('forecast_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('cost_variance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('remaining_budget', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_project_cost_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funding_type', models.CharField(blank=True, default='', max_length=255)),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_project_funding',
            },
        ),
        migrations.CreateModel(
            name='ProjectFundingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_project_funding_transaction',
            },
        ),
        migrations.CreateModel(
            name='ProjectWIPSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('completion_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('recognized_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('recognized_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('wip_asset_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('accrued_billing_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unbilled_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_project_wip_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RecurringPaymentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=255)),
                ('next_run_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_recurring_payment_rule',
            },
        ),
        migrations.CreateModel(
            name='RecurringPaymentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('run_status', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'fin_recurring_payment_run',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_direction', models.CharField(blank=True, default='', max_length=255)),
                ('tax_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_tax_transaction',
            },
        ),
        migrations.CreateModel(
            name='UnitCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_unit_code', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('machine_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('overhead_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'fin_unit_cost_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_type', models.CharField(blank=True, default='', max_length=255)),
                ('normal_balance', models.CharField(blank=True, default='', max_length=255)),
                ('allow_manual_posting', models.BooleanField(default=False)),
                ('reconciliation_required', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_account_company_set', to='core.company')),
            ],
            options={
                'db_table': 'fin_account',
            },
        ),
    ]
