# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_account_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, db_column='parent_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_account_parent_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankaccount_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankaccount_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_account',
            field=models.ForeignKey(blank=True, db_column='ledger_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankaccount_ledger_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankaccount_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='bank_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankstatement_bank_account_set', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='bank_statement',
            field=models.ForeignKey(blank=True, db_column='bank_statement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankstatementline_bank_statement_set', to='finance.bankstatement'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, db_column='bank_statement_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankreconciliation_bank_statement_line_set', to='finance.bankstatementline'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='payment_term',
            field=models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_payment_term_set', to='master_data.paymentterm'),
        ),
    ]
