# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0001_initial'),
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_purchase_order_set', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocument_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='arapschedule',
            name='billing_document',
            field=models.ForeignKey(blank=True, db_column='billing_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_arapschedule_billing_document_set', to='finance.billingdocument'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='billing_document',
            field=models.ForeignKey(blank=True, db_column='billing_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_billing_document_set', to='finance.billingdocument'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_cost_center_set', to='master_data.costcenter'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='tax_code',
            field=models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_tax_code_set', to='master_data.taxcode'),
        ),
        migrations.AddField(
            model_name='billingdocumentline',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_billingdocumentline_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgetline_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(blank=True, db_column='budget_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgetline_budget_set', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgetline_cost_center_set', to='master_data.costcenter'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgetline_department_set', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgetline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='costbaseline',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaseline_approved_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costbaseline',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaseline_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='costbaseline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaseline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='costbaselineline',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaselineline_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='costbaselineline',
            name='cost_baseline',
            field=models.ForeignKey(blank=True, db_column='cost_baseline_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaselineline_cost_baseline_set', to='finance.costbaseline'),
        ),
        migrations.AddField(
            model_name='costbaselineline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaselineline_cost_center_set', to='master_data.costcenter'),
        ),
        migrations.AddField(
            model_name='costbaselineline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costbaselineline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='costvariance',
            name='cost_baseline_line',
            field=models.ForeignKey(blank=True, db_column='cost_baseline_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costvariance_cost_baseline_line_set', to='finance.costbaselineline'),
        ),
        migrations.AddField(
            model_name='costvariance',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costvariance_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='creditfacility',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_creditfacility_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='creditfacility',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_creditfacility_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='creditfacility',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_creditfacility_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_financialsnapshot_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_financialsnapshot_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='costvariance',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_costvariance_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fiscalyear_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_column='fiscal_year_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fiscalperiod_fiscal_year_set', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_column='fiscal_year_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_fiscal_year_set', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journal_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(blank=True, db_column='journal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_journal_set', to='finance.journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of_entry',
            field=models.ForeignKey(blank=True, db_column='reversal_of_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_reversal_of_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalentry_source_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_cost_center_set', to='master_data.costcenter'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_department_set', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='source_document_line',
            field=models.ForeignKey(blank=True, db_column='source_document_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_source_document_line_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, db_column='transaction_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_transaction_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_journalline_warehouse_set', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='journal_line',
            field=models.ForeignKey(blank=True, db_column='journal_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankreconciliation_journal_line_set', to='finance.journalline'),
        ),
        migrations.AddField(
            model_name='overheadallocation',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadallocation_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='overheadallocation',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadallocation_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='overheadallocation',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadallocation_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='overheadallocation',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadallocation_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='overheadrule',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadrule_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='overheadrule',
            name='source_account',
            field=models.ForeignKey(blank=True, db_column='source_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadrule_source_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='overheadrule',
            name='target_cost_center',
            field=models.ForeignKey(blank=True, db_column='target_cost_center_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadrule_target_cost_center_set', to='master_data.costcenter'),
        ),
        migrations.AddField(
            model_name='overheadallocation',
            name='overhead_rule',
            field=models.ForeignKey(blank=True, db_column='overhead_rule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overheadallocation_overhead_rule_set', to='finance.overheadrule'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='bank_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_bank_account_set', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_bankreconciliation_payment_set', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='billing_document',
            field=models.ForeignKey(blank=True, db_column='billing_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_paymentallocation_billing_document_set', to='finance.billingdocument'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_paymentallocation_payment_set', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_paymentallocation_schedule_set', to='finance.arapschedule'),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_periodclosing_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='executed_by',
            field=models.ForeignKey(blank=True, db_column='executed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_periodclosing_executed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_periodclosing_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='projectcostsnapshot',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectcostsnapshot_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfunding_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfunding_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='funding_source_party',
            field=models.ForeignKey(blank=True, db_column='funding_source_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfunding_funding_source_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfunding_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfundingtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_column='journal_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfundingtransaction_journal_entry_set', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='projectfundingtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfundingtransaction_payment_set', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='projectfundingtransaction',
            name='project_funding',
            field=models.ForeignKey(blank=True, db_column='project_funding_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectfundingtransaction_project_funding_set', to='finance.projectfunding'),
        ),
        migrations.AddField(
            model_name='projectwipsnapshot',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectwipsnapshot_fiscal_period_set', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='projectwipsnapshot',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_projectwipsnapshot_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrule',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='bank_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrule_bank_account_set', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrule',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrule_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrule',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrule_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrule',
            name='expense_account',
            field=models.ForeignKey(blank=True, db_column='expense_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrule_expense_account_set', to='finance.account'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrule',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrule_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrun',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrun_payment_set', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='recurringpaymentrun',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, db_column='recurring_rule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_recurringpaymentrun_recurring_rule_set', to='finance.recurringpaymentrule'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='billing_document',
            field=models.ForeignKey(blank=True, db_column='billing_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_taxtransaction_billing_document_set', to='finance.billingdocument'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='billing_document_line',
            field=models.ForeignKey(blank=True, db_column='billing_document_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_taxtransaction_billing_document_line_set', to='finance.billingdocumentline'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='tax_code',
            field=models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_taxtransaction_tax_code_set', to='master_data.taxcode'),
        ),
        migrations.AddField(
            model_name='unitcostsnapshot',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_unitcostsnapshot_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='unitcostsnapshot',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_unitcostsnapshot_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='unitcostsnapshot',
            name='production_order',
            field=models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_unitcostsnapshot_production_order_set', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='unitcostsnapshot',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_unitcostsnapshot_project_set', to='projects.project'),
        ),
    ]
