# Generated by Django 5.2.17 on 2026-08-13 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0005_project_funding_workflow'),
        ('master_data', '0001_initial'),
        ('projects', '0007_membership_task_authorization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(blank=True, default='PROJECT_COMPLETED', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tax_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tax_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('status', models.CharField(blank=True, default='DRAFT', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_billing_proposals', to=settings.AUTH_USER_MODEL)),
                ('billing_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_proposal', to='finance.billingdocument')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_proposals', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_billing_proposals', to='master_data.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_proposals', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_billing_proposals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_proposals', to='core.tenant')),
            ],
            options={
                'db_table': 'fin_billing_proposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='fin_billing_queue')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, default='MANUAL', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cost_element', models.CharField(blank=True, default='OTHER', max_length=32)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, default=1, max_digits=24)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('status', models.CharField(blank=True, default='CAPTURED', max_length=32)),
                ('validation_note', models.TextField(blank=True, default='')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_entries', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_cost_entries', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_entries', to='finance.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_project_cost_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='projects.project')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_entries', to='core.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_project_cost_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_project_cost_entry',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'project', 'status'], name='fin_cost_inbox_lookup')],
            },
        ),
    ]
