# Generated by Django 5.2.17 on 2026-08-14 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0006_billingproposal_projectcostentry'),
        ('procurement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtransaction',
            name='billing_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='ntpn',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='status',
            field=models.CharField(blank=True, default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_tax_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='validation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InvoiceVarianceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variance_type', models.CharField(blank=True, default='MIXED', max_length=32)),
                ('total_variance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('status', models.CharField(blank=True, default='OPEN', max_length=32)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_invoice_variances', to=settings.AUTH_USER_MODEL)),
                ('billing_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variance_cases', to='finance.billingdocument')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_variance_cases', to='core.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_invoice_variances', to=settings.AUTH_USER_MODEL)),
                ('three_way_match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='variance_case', to='procurement.threewaymatch')),
            ],
            options={
                'db_table': 'fin_invoice_variance_case',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='fin_invoice_variance_queue')],
            },
        ),
    ]
