# Generated by Django 5.2.17 on 2026-08-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0007_taxtransaction_billing_code_taxtransaction_ntpn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='core.company'),
        ),
    ]
