# Generated by Django 5.2.17 on 2026-08-21 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0008_taxtransaction_company'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('used_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_term_days', models.IntegerField(default=30)),
                ('status', models.CharField(default='APPROVED', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_limits', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_limits', to='master_data.party')),
            ],
            options={
                'db_table': 'fin_customer_credit_limit',
                'ordering': ['-updated_at'],
            },
        ),
    ]
