from django.contrib import admin

from . import models

admin.site.register(models.FiscalYear)
admin.site.register(models.FiscalPeriod)
admin.site.register(models.Account)
admin.site.register(models.Journal)
admin.site.register(models.JournalEntry)
admin.site.register(models.JournalLine)
admin.site.register(models.BillingDocument)
admin.site.register(models.BillingDocumentLine)
admin.site.register(models.ARAPSchedule)
admin.site.register(models.Payment)
admin.site.register(models.PaymentAllocation)
admin.site.register(models.BankAccount)
admin.site.register(models.BankStatement)
admin.site.register(models.BankStatementLine)
admin.site.register(models.BankReconciliation)
admin.site.register(models.TaxTransaction)
admin.site.register(models.Budget)
admin.site.register(models.BudgetLine)
admin.site.register(models.PeriodClosing)
admin.site.register(models.FinancialSnapshot)
admin.site.register(models.UnitCostSnapshot)
admin.site.register(models.RecurringPaymentRule)
admin.site.register(models.RecurringPaymentRun)
admin.site.register(models.CreditFacility)
admin.site.register(models.ProjectWIPSnapshot)
admin.site.register(models.ProjectFunding)
admin.site.register(models.ProjectFundingTransaction)
admin.site.register(models.CostBaseline)
admin.site.register(models.CostBaselineLine)
admin.site.register(models.CostVariance)
admin.site.register(models.OverheadRule)
admin.site.register(models.OverheadAllocation)
admin.site.register(models.ProjectCostSnapshot)
