# Generated by Django 5.2.17 on 2026-08-05 08:27

import apps.accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(blank=True, default='', max_length=255)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_approval_limit',
            },
        ),
        migrations.CreateModel(
            name='DataScopePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('scope_type', models.CharField(blank=True, default='', max_length=255)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_data_scope_policy',
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('masking_type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'iam_field_permission',
            },
        ),
        migrations.CreateModel(
            name='InformationShareRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module_code', models.CharField(blank=True, default='', max_length=255)),
                ('target_module_code', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('field_set_code', models.CharField(blank=True, default='', max_length=255)),
                ('share_direction', models.CharField(blank=True, default='', max_length=255)),
                ('filter_json', models.JSONField(blank=True, default=dict)),
                ('access_level', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_information_share_rule',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('module_code', models.CharField(blank=True, default='', max_length=255)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('action_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'iam_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(blank=True, default='', max_length=255)),
                ('role_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'iam_role',
            },
        ),
        migrations.CreateModel(
            name='RoleDataScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(blank=True, default='', max_length=255)),
                ('can_export', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_role_data_scope',
            },
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inheritance_mode', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_role_hierarchy',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iam_role_permission',
            },
        ),
        migrations.CreateModel(
            name='UserProjectAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_role', models.CharField(blank=True, default='', max_length=255)),
                ('access_level', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iam_user_project_access',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'iam_user_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='ACTIVE', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'iam_user',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
