# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallimit',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_approvallimit_currency_set', to='master_data.currency'),
        ),
        migrations.AddField(
            model_name='approvallimit',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_approvallimit_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datascopepolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_datascopepolicy_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='informationsharerule',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_informationsharerule_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_role_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_fieldpermission_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='approvallimit',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_approvallimit_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='roledatascope',
            name='policy',
            field=models.ForeignKey(blank=True, db_column='policy_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_roledatascope_policy_set', to='accounts.datascopepolicy'),
        ),
        migrations.AddField(
            model_name='roledatascope',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_roledatascope_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolehierarchy',
            name='child_role',
            field=models.ForeignKey(blank=True, db_column='child_role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_rolehierarchy_child_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolehierarchy',
            name='parent_role',
            field=models.ForeignKey(blank=True, db_column='parent_role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_rolehierarchy_parent_role_set', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, db_column='permission_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_rolepermission_permission_set', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_rolepermission_role_set', to='accounts.role'),
        ),
    ]
