/**
 * Ready-to-test demo user accounts configuration (Arsalynk & Demo Profiles)
 */

export const DEMO_USERS = [
  // Arsalynk Production & Database Accounts
  {
    email: "admin@arsalynk.id",
    password: "DummyPass123!",
    name: "Arsalynk Administrator",
    category: "exec",
    roleLabel: "ADMIN · Full System Access (admin@arsalynk.id)",
    icon: "👑",
  },
  {
    email: "director@arsalynk.id",
    password: "DummyPass123!",
    name: "Executive Director",
    category: "exec",
    roleLabel: "DIRECTOR · Executive & Credit Override (director@arsalynk.id)",
    icon: "🏛️",
  },
  {
    email: "manager@arsalynk.id",
    password: "DummyPass123!",
    name: "Operational Manager",
    category: "crm",
    roleLabel: "MANAGER · CRM & Quotation Approval (manager@arsalynk.id)",
    icon: "👔",
  },
  {
    email: "sales@arsalynk.id",
    password: "DummyPass123!",
    name: "Commercial & Sales",
    category: "crm",
    roleLabel: "SALES · Inquiry, Estimating & Deals (sales@arsalynk.id)",
    icon: "🧑‍💼",
  },
  {
    email: "pm@arsalynk.id",
    password: "DummyPass123!",
    name: "Project Manager",
    category: "pm",
    roleLabel: "PM · Stage Gates, WBS & Cost Handoff (pm@arsalynk.id)",
    icon: "🏗️",
  },
  {
    email: "supervisor@arsalynk.id",
    password: "DummyPass123!",
    name: "Field Supervisor",
    category: "pm",
    roleLabel: "SUPERVISOR · Field Timesheet & Issues (supervisor@arsalynk.id)",
    icon: "👷",
  },
  {
    email: "finance@arsalynk.id",
    password: "DummyPass123!",
    name: "Accounting & Finance",
    category: "fin",
    roleLabel: "FINANCE · Cost Inbox, AP/AR & Ledger (finance@arsalynk.id)",
    icon: "💼",
  },
  {
    email: "qc@arsalynk.id",
    password: "DummyPass123!",
    name: "Quality Control",
    category: "pm",
    roleLabel: "QC · Inspection & Quality (qc@arsalynk.id)",
    icon: "🔬",
  },
  {
    email: "warehouse@arsalynk.id",
    password: "DummyPass123!",
    name: "Warehouse Logistics",
    category: "pm",
    roleLabel: "WAREHOUSE · Inventory & Materials (warehouse@arsalynk.id)",
    icon: "📦",
  },

  // Prototype Mirror Accounts
  {
    email: "dummy.admin@example.com",
    password: "DummyPass123!",
    name: "Dummy Administrator",
    category: "exec",
    roleLabel: "ROLE-ADMIN · Prototype Admin",
    icon: "👑",
  },
  {
    email: "executive.demo@erp.local",
    password: "DummyPass123!",
    name: "Executive Demo",
    category: "exec",
    roleLabel: "EXECUTIVE · Direksi & Cross-Module",
    icon: "🏛️",
  },
  {
    email: "dummy.manager@example.com",
    password: "DummyPass123!",
    name: "Dummy Operational Manager",
    category: "crm",
    roleLabel: "ROLE-MANAGER · CRM Manager",
    icon: "👔",
  },
  {
    email: "dummy.staff@example.com",
    password: "DummyPass123!",
    name: "Dummy Operational Staff",
    category: "crm",
    roleLabel: "ROLE-STAFF · CRM Staff",
    icon: "🧑‍💼",
  },
  {
    email: "project.manager.demo@erp.local",
    password: "DummyPass123!",
    name: "Project Manager Demo",
    category: "pm",
    roleLabel: "PROJECT_MANAGEMENT · PM Demo",
    icon: "🏗️",
  },
  {
    email: "assignee.demo@erp.local",
    password: "DummyPass123!",
    name: "Project Assignee Demo",
    category: "pm",
    roleLabel: "PROJECT_ASSIGNEE · Field Demo",
    icon: "👷",
  },
  {
    email: "finance.demo@erp.local",
    password: "DummyPass123!",
    name: "Finance Demo",
    category: "fin",
    roleLabel: "ACCOUNTING_FINANCE · Finance Maker",
    icon: "💼",
  },
  {
    email: "finance.approver@example.com",
    password: "DummyPass123!",
    name: "Finance Approver",
    category: "fin",
    roleLabel: "FINANCE · Approver Demo",
    icon: "✍️",
  },
];
