# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('credential_reference', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'crm_channel_account',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_conversation_id', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_type', models.CharField(blank=True, default='', max_length=255)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_conversation_participant',
            },
        ),
        migrations.CreateModel(
            name='CreditStatusSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('outstanding_receivable', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('overdue_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('available_credit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('risk_category', models.CharField(blank=True, default='', max_length=255)),
                ('credit_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_credit_status_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(blank=True, default='', max_length=255)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('decision', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_executive_approval',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(blank=True, default='', max_length=255)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('nps_score', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_feedback',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_source', models.CharField(blank=True, default='', max_length=255)),
                ('lead_status', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('message_type', models.CharField(blank=True, default='', max_length=255)),
                ('message_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_message',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_message_attachment',
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=255)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=255)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_message_delivery_status',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_stage', models.CharField(blank=True, default='', max_length=255)),
                ('probability_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('expected_margin', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_opportunity',
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'crm_opportunity_product',
            },
        ),
        migrations.CreateModel(
            name='OpportunityStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_opportunity_stage_history',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('pipeline_name', models.CharField(blank=True, default='', max_length=255)),
                ('default_pipeline', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_pipeline',
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_code', models.CharField(blank=True, default='', max_length=255)),
                ('stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('position_order', models.IntegerField(blank=True, null=True)),
                ('default_probability_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('closed_won', models.BooleanField(default=False)),
                ('closed_lost', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_pipeline_stage',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('survey_name', models.CharField(blank=True, default='', max_length=255)),
                ('survey_type', models.CharField(blank=True, default='', max_length=255)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('text_answer', models.TextField(blank=True, default='')),
                ('option_answer', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'crm_survey_answer',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, default='', max_length=255)),
                ('answer_type', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('position_order', models.IntegerField(blank=True, null=True)),
                ('option_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'crm_survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'crm_survey_response',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_activity_assigned_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_activity',
            },
        ),
    ]
