# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_activity_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_channelaccount_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_channelaccount_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_user',
            field=models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_assigned_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='channel_account',
            field=models.ForeignKey(blank=True, db_column='channel_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_channel_account_set', to='crm.channelaccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_contact_set', to='master_data.contact'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_party',
            field=models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_customer_party_set', to='master_data.party'),
        ),
    ]
