# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0002_initial'),
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='service_case',
            field=models.ForeignKey(blank=True, db_column='service_case_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_service_case_set', to='service.case'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversationparticipant_contact_set', to='master_data.contact'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversationparticipant_conversation_set', to='crm.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversationparticipant_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversationparticipant_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditstatussnapshot',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_creditstatussnapshot_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='creditstatussnapshot',
            name='customer_party',
            field=models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_creditstatussnapshot_customer_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='approver_user',
            field=models.ForeignKey(blank=True, db_column='approver_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_approver_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='contract',
            field=models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_contract_set', to='sales.contract'),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='quotation',
            field=models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_quotation_set', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_requested_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_contact_set', to='master_data.contact'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_party',
            field=models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_customer_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='delivery',
            field=models.ForeignKey(blank=True, db_column='delivery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_delivery_set', to='sales.delivery'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service_case',
            field=models.ForeignKey(blank=True, db_column='service_case_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_feedback_service_case_set', to='service.case'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_message_conversation_set', to='crm.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_party',
            field=models.ForeignKey(blank=True, db_column='sender_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_message_sender_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(blank=True, db_column='sender_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_message_sender_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_messageattachment_file_set', to='core.file'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_messageattachment_message_set', to='crm.message'),
        ),
        migrations.AddField(
            model_name='messagedeliverystatus',
            name='message',
            field=models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_messagedeliverystatus_message_set', to='crm.message'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_party',
            field=models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunity_customer_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunity_document_set', to='core.businessdocument'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunity_lead_set', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunity_owner_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executiveapproval',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executiveapproval_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_conversation_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_activity_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunityproduct_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunityproduct_product_set', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunityproduct_uom_set', to='master_data.uom'),
        ),
        migrations.AddField(
            model_name='opportunitystagehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunitystagehistory_changed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunitystagehistory',
            name='opportunity',
            field=models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunitystagehistory_opportunity_set', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_pipeline_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_pipeline_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_column='pipeline_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_pipelinestage_pipeline_set', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='opportunitystagehistory',
            name='from_stage',
            field=models.ForeignKey(blank=True, db_column='from_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunitystagehistory_from_stage_set', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='opportunitystagehistory',
            name='to_stage',
            field=models.ForeignKey(blank=True, db_column='to_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunitystagehistory_to_stage_set', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_survey_company_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_survey_tenant_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(blank=True, db_column='survey_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyquestion_survey_set', to='crm.survey'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question',
            field=models.ForeignKey(blank=True, db_column='question_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyanswer_question_set', to='crm.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyresponse_contact_set', to='master_data.contact'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='customer_party',
            field=models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyresponse_customer_party_set', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyresponse_project_set', to='projects.project'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyresponse_sales_order_set', to='sales.order'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, db_column='survey_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyresponse_survey_set', to='crm.survey'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='response',
            field=models.ForeignKey(blank=True, db_column='response_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_surveyanswer_response_set', to='crm.surveyresponse'),
        ),
    ]
