# Generated by Django 5.2.17 on 2026-08-14 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0003_initial'),
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunities', to='core.company'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_opportunities', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquiry_number', models.CharField(blank=True, default='', max_length=64)),
                ('source_channel', models.CharField(blank=True, default='MANUAL', max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='NEW', max_length=32)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiries', to='core.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiries', to='master_data.contact')),
                ('customer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiries', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiries', to='core.businessdocument')),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inquiry', to='crm.opportunity')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_crm_inquiries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiries', to='core.tenant')),
            ],
            options={
                'db_table': 'crm_customer_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_workflow_events', to='core.company')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='crm.opportunity')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='crm.customerinquiry')),
            ],
            options={
                'db_table': 'crm_workflow_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(blank=True, default='', max_length=64)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('direct_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('overhead_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('contingency_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('markup_percent', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('offered_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('margin_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('margin_percent', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('status', models.CharField(blank=True, default='DRAFT', max_length=32)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_crm_estimates', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_cost_estimates', to='core.company')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_estimates', to='crm.opportunity')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_cost_estimates', to='core.tenant')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_estimates', to='crm.customerinquiry')),
            ],
            options={
                'db_table': 'crm_cost_estimate',
            },
        ),
        migrations.CreateModel(
            name='InquiryRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_type', models.CharField(blank=True, default='PRODUCT', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('specification_json', models.JSONField(blank=True, default=dict)),
                ('quantity', models.DecimalField(decimal_places=6, default=1, max_digits=24)),
                ('target_unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('status', models.CharField(blank=True, default='DRAFT', max_length=32)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crm.customerinquiry')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiry_requirements', to='master_data.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_inquiry_requirements', to='master_data.uom')),
            ],
            options={
                'db_table': 'crm_inquiry_requirement',
            },
        ),
        migrations.CreateModel(
            name='CostEstimateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_element', models.CharField(blank=True, default='MATERIAL', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, default=1, max_digits=24)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('calculation_source', models.CharField(blank=True, default='MANUAL', max_length=32)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.costestimate')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_estimate_lines', to='master_data.product')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='crm.inquiryrequirement')),
            ],
            options={
                'db_table': 'crm_cost_estimate_line',
            },
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tax_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('margin_percent', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_quotation_versions', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_versions', to='crm.costestimate')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sales.quotation')),
            ],
            options={
                'db_table': 'crm_quotation_version',
            },
        ),
        migrations.CreateModel(
            name='QuotationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, default='EMAIL', max_length=32)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='QUEUED', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sales.quotation')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='crm.quotationversion')),
            ],
            options={
                'db_table': 'crm_quotation_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='customerinquiry',
            index=models.Index(fields=['company', 'status'], name='crm_inquiry_queue'),
        ),
        migrations.AddConstraint(
            model_name='costestimate',
            constraint=models.UniqueConstraint(fields=('inquiry', 'version_number'), name='crm_estimate_inquiry_version'),
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='crm_quotation_version_unique'),
        ),
    ]
