# Generated by Django 5.2.17 on 2026-08-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0004_opportunity_closed_at_opportunity_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveapproval',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_executive_approvals', to='core.company'),
        ),
    ]
