# Generated by Django 5.2.17 on 2026-08-21 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0005_executiveapproval_company'),
        ('master_data', '0001_initial'),
        ('projects', '0014_projectevmrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('feedback_type', models.CharField(default='PROJECT_COMPLETION', max_length=64)),
                ('aspect_quality', models.IntegerField(default=5)),
                ('aspect_timeline', models.IntegerField(default=5)),
                ('aspect_communication', models.IntegerField(default=5)),
                ('comments', models.TextField(blank=True, default='')),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_feedbacks', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_feedbacks', to='master_data.party')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedbacks', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedbacks', to='crm.opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedbacks', to='projects.project')),
            ],
            options={
                'db_table': 'crm_customer_feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
