import resourceInventory from './resource-catalog.generated.json';
// Reviewed against the ERP routes and forms. Versioned with the application.
export const moduleKnowledge = [
  { module: 'GENERAL', title: 'Dashboard', path: '/dashboard', keywords: /dashboard|beranda/i, content: 'Dashboard menampilkan konteks perusahaan aktif dan kartu permintaan. Data serta aksi yang tersedia mengikuti role aktif.' },
  { module: 'PROJECTS', title: 'Projects', path: '/projects', keywords: /proyek|project|wbs|mingguan|assignment/i, content: 'Hierarki eksekusi: Project → Main Task → Weekly Task → Daily Task. Assignment Main Task menentukan peserta; Weekly Task memiliki assignee; Daily Task memiliki owner. Progres dihitung dari checklist dan digulung ke hierarki induk. Output hasil wajib untuk penyelesaian task; alasan wajib untuk task blocked. Perubahan assignment/transfer memakai aksi khusus dengan validasi authority.' },
  { module: 'PROJECTS', title: 'Tugas Harian', path: '/tasks', keywords: /tugas|task|timesheet/i, content: 'Tugas Harian adalah eksekusi personal. Pembuatan task memerlukan assignment Main Task dan ownership Weekly Task. Timesheet terhubung ke employee; master_employee.user_id menghubungkan employee dengan akun user. Status task aktual mengikuti aturan checklist backend.' },
  { module: 'FINANCE', title: 'Finance & Accounting', path: '/finance', keywords: /finance|keuangan|wip|billing|piutang|jurnal|biaya/i, content: 'Halaman mencakup costing & WIP, funding proyek, tagihan vendor, billing termin, piutang, kas & bank, buku besar, laporan keuangan, rekonsiliasi, perpajakan, aset, tutup buku dan audit trail. Biaya proyek aktual asisten hanya mengakui cost entry VALIDATED, APPROVED, POSTED_TO_WIP. Draft/rejected tidak dijumlahkan. Director memiliki akses preview Finance; mutasi operasional dibatasi backend.' },
  { module: 'CRM', title: 'CRM & Commercial', path: '/crm', keywords: /crm|commercial|komersial|customer|pelanggan|deal|inquiry/i, content: 'Halaman mencakup Dashboard, Deals & Credit, Incoming Inquiry, Accounts dan Engagement. Estimating & Quoting serta Contracts & Orders memerlukan modul SALES; Support & Garansi memerlukan SERVICE. Keberadaan tab tidak memberikan permission untuk mengambil data.' },
  { module: 'REPORTING', title: 'Reporting & Observability', path: '/reporting', keywords: /reporting|laporan|kehadiran|attendance/i, content: 'Tab laporan: Executive View, Project P&L, General Ledger, Ringkasan Berkala, Kehadiran dan Operasional. Sumber finance/proyek memerlukan akses modul asal; akses Reporting tidak memberi akses Finance secara otomatis.' },
  { module: 'REQUESTS', title: 'Requests & Meetings', path: '/requests', keywords: /request|meeting|rapat|notulen/i, content: 'Permintaan dan meeting memiliki participant, agenda, minutes, decision serta action item. Editor notulensi dibatasi ke notulis yang ditunjuk. Draft dan publikasi adalah aksi terpisah.' },
  { module: 'ANALYTICS', title: 'Enterprise Repository & Document Catalog', path: '/resources', keywords: /repository|arsip|dokumen|resources/i, content: 'Halaman merupakan pusat arsip digital, katalog transaksi dan dokumentasi operasional. Data katalog mengikuti akses sumbernya.' },
  { module: 'PROCUREMENT', title: 'Procurement', path: '', keywords: /procurement|pengadaan|purchase|requisition|rfq/i, content: 'API pengadaan mencakup purchase requisition dan baris, RFQ, supplier quotation, purchase order dan baris, goods receipt dan baris. Convert-to-RFQ adalah aksi khusus berdasarkan requisition di company aktif; RFQ yang sudah ada dikembalikan. Three-way-match memeriksa purchase order, goods receipt, dan supplier invoice melalui service khusus; hasil matching bersifat read-only.' },
  { module: 'INVENTORY', title: 'Inventory', path: '', keywords: /inventory|inventori|stok|stock|warehouse|fifo/i, content: 'Posting stock move memvalidasi jenis RECEIPT, ISSUE atau TRANSFER, lokasi, product FIFO dan UOM dasar, kuantitas positif serta ketersediaan FIFO layer/stok bebas. Posting membentuk ledger dan balance; movement yang sudah selesai tidak boleh diubah sebagai draft. Lot/serial memerlukan posting traceability khusus dan tidak boleh dianggap stok umum.' },
  { module: 'MANUFACTURING', title: 'Manufacturing', path: '', keywords: /manufacturing|manufaktur|produksi|production|work order/i, content: 'Production order memiliki aksi release dan issue-materials; work order memiliki start dan complete. Issue mensyaratkan order RELEASED/IN_PROGRESS, material plan dan stock ISSUE yang sesuai. Complete work order mensyaratkan status IN_PROGRESS, seluruh inspection selesai dan PASS, serta completed+rejected quantity sesuai planned quantity. Material yang sudah di-issue dibatasi terhadap perubahan/hapus.' },
  { module: 'QUALITY', title: 'Quality', path: '', keywords: /quality|kualitas|inspection|inspeksi|nonconformance|capa/i, content: 'Resource mencakup quality plan dan point, inspection dan result, nonconformance serta corrective action. Complete inspection memakai service khusus. Result hanya boleh dicatat pada inspection aktif dalam company yang sama; hasil inspection selesai bersifat immutable dan tidak boleh dipindahkan ke inspection lain.' },
  { module: 'ASSETS', title: 'Assets', path: '', keywords: /assets|aset|depreciation|penyusutan|disposal/i, content: 'Penyusutan dan disposal merupakan aksi domain, bukan perubahan status biasa. Disposal mensyaratkan aset ACTIVE, tanggal dan hasil penjualan valid, akun GL lengkap dan periode fiskal OPEN. Nilai buku, perolehan serta akumulasi penyusutan harus konsisten; service memeriksa agar aset tidak dilepas dua kali.' },
  { module: 'LOGISTICS', title: 'Logistics', path: '', keywords: /logistics|logistik|shipment|pengiriman|tracking|delivery/i, content: 'API mencakup shipment, shipment line, tracking event dan proof of delivery. Aksi proof-of-delivery memeriksa shipment di company aktif dan mencatat receiver, waktu penerimaan, remarks serta verification status. Data yang belum diambil dari ERP tidak boleh dianggap bukti pengiriman.' },
  { module: 'SERVICE', title: 'Service & Support', path: '', keywords: /service|layanan|support|garansi|case/i, content: 'Resource mencakup case, case message, case approval dan resolution. Aksi resolve memeriksa case dalam company aktif, mengubah status menjadi RESOLVED dan mencatat resolved_at. Status aktual harus dibaca ulang setelah perubahan.' },
  { module: 'SALES', title: 'Sales', path: '', keywords: /sales|penjualan|quotation|penawaran|order|kontrak/i, content: 'Quotation memiliki aksi submit-approval, send dan customer-decision (ACCEPTED/REJECTED); order memiliki confirm, allocate dan convert-to-project; delivery memiliki dispatch. Convert-to-project menghubungkan sales_order_id dan customer_party_id, memeriksa company serta memakai proyek yang sudah ada. Transisi workflow menggunakan aksi khusus; CRUD biasa tidak menggantikan validasi transisi.' },
  { module: 'IMPLEMENTATION', title: 'Implementation', path: '', keywords: /implementation|implementasi|release|gtm|test cycle/i, content: 'API implementasi mencakup release, phase dan phase item, workflow dan workflow stage, work item, test cycle serta GTM milestone. Field dan relasi aktual ditemukan dari schema database; keberadaan resource tidak membuktikan ada aksi deploy/publish otomatis.' },
  { module: 'MASTER_DATA', title: 'Master Data', path: '', keywords: /master data|employee|pegawai|currency|party|product|produk/i, content: 'Master data menjadi referensi bagi transaksi: party/customer/vendor, product dan UOM, currency, employee dan referensi organisasi. employee.user_id menghubungkan data pegawai dengan akun. Relasi user/company dan foreign key harus divalidasi; nama mirip tidak membuktikan identitas yang sama.' },
] as const;

export function systemKnowledgeAnswer(message: string, enabledModules: string[]) {
  const available = moduleKnowledge.filter(item => enabledModules.includes(item.module));
  const matches = /seluruh|semua|fitur sistem|modul sistem/i.test(message) ? available : available.filter(item => item.keywords.test(message));
  if (!matches.length) return 'Referensi fitur tersebut belum tersedia dalam cakupan modul aktif Anda. Tidak ada kesimpulan mengenai data aktual yang dapat dibuat.';
  return matches.map(item => {
    const resources = resourceInventory.resources.filter(resource => resource.module === item.module);
    const reference = resources.length ? `\n\nResource API aktual: ${resources.map(resource => resource.key).join(', ')}. Akses baca/tulis tetap diperiksa backend pada eksekusi.` : '';
    return `${item.title}\n\n${item.content}${item.path ? `\n\n[Buka ${item.title}](${item.path})` : ''}${reference}`;
  }).join('\n\n---\n\n') + '\n\nSumber: route, form, service dan katalog schema ERP. Data aktual harus dibaca dari database.';
}
export const procedures = [
  { id: 'reports', title: 'Laporan kerja', keywords: /laporan|report/i, path: '/reporting',
    content: 'Buka menu Laporan. Untuk laporan berkala, buka Tugas Harian lalu pilih Laporan Berkala. Data yang muncul mengikuti peran dan akses Anda. Jika menu tidak tersedia, hubungi admin perusahaan.' },
  { id: 'timesheet', title: 'Timesheet dan lembur', keywords: /timesheet|timer|lembur|jam kerja/i, path: '/tasks',
    content: 'Sebagai Staff, buka Tugas Harian lalu bagian Timesheet & Lembur Saya. Pilih proyek, tanggal kerja, dan task bila diperlukan, lalu mulai timer kerja. Hentikan timer saat selesai. Untuk lembur, mulai dan hentikan timer lembur serta isi alasannya. Kirim catatan setelah timer berhenti, lalu periksa riwayat dan status approval. Durasi dihitung server dari waktu mulai/selesai; jangan mengisi durasi manual.' },
  { id: 'invoice', title: 'Invoice dan billing termin', keywords: /invoice|faktur|billing|tagihan/i, path: '/finance',
    content: 'Untuk faktur penagihan klien, buka Finance lalu tab Billing Termin. Pilih Buat Proposal dan isi data yang diminta pada formulir. Proposal DRAFT diproses melalui Submit, lalu pihak yang berwenang melakukan Approve. Proposal APPROVED dapat diproses melalui Terbitkan Billing. Periksa dokumen dan status hasil sebelum mencatat pembayaran. Aksi yang tersedia mengikuti peran, entitlement, dan status dokumen; hubungi admin jika tab atau tombol tidak tersedia. Panduan ini tidak menyetujui atau menerbitkan invoice secara otomatis.' },
  { id: 'minutes', title: 'Notulensi meeting', keywords: /notulen|notulis|meeting|rapat/i, path: '/requests',
    content: 'Buka Requests & Meetings dan pilih meeting. Periksa nama Notulis. Hanya notulis yang ditunjuk dapat membuka editor. Pilih Tambah Notulensi atau Edit Notulensi, isi pembahasan, ringkasan, keputusan dan tindak lanjut. Simpan draft atau pilih Publikasikan setelah diperiksa.' },
  { id: 'tasks', title: 'Tugas harian', keywords: /tugas|task|pekerjaan/i, path: '/tasks',
    content: 'Buka Tugas Harian. Pilih task yang ditugaskan kepada Anda, catat hasil pekerjaan, bukti atau kendala pada formulir yang tersedia, lalu kirim pembaruan. Periksa status pengajuan setelah tersimpan.' },
  { id: 'leave', title: 'Pengajuan cuti', keywords: /cuti|izin|leave/i, path: '/dashboard',
    content: 'Buka Dashboard, cari Kartu Permintaan Aktif, lalu pilih Tambahkan Kartu. Pada Request Type pilih Leave Request. Isi tanggal pelaksanaan dan Request Details; lampirkan tautan dokumen bila diperlukan. Pilih Simpan Draft untuk menyimpan sementara atau Kirim Request untuk mengajukan. Setelah terkirim, status dapat dilihat pada kartu permintaan. Persetujuan dilakukan oleh pejabat yang berwenang sesuai alur perusahaan.' },
] as const;

export function helperAnswer(message: string): string {
  const matches = procedures.filter(item => item.keywords.test(message));
  if (!matches.length) return 'Saya dapat membantu panduan pengajuan cuti, laporan kerja, tugas harian, timesheet, dan notulensi meeting. Sebutkan fitur yang ingin Anda gunakan. Untuk data terkini, tanyakan progres proyek, task terlambat, biaya proyek, KPI, atau tiket support sesuai akses Anda.';
  return matches.map(item => `${item.title}\n\n${item.content}${item.path ? `\n\n[Buka ${item.title}](${item.path})` : ''}\n\nSumber: panduan ERP • versi 2026-09-30.`).join('\n\n---\n\n');
}
