from django.contrib import admin

from . import models

admin.site.register(models.Project)
admin.site.register(models.Member)
admin.site.register(models.Task)
admin.site.register(models.TaskDependency)
admin.site.register(models.Milestone)
admin.site.register(models.MaterialRequirement)
admin.site.register(models.BudgetLine)
admin.site.register(models.Timesheet)
admin.site.register(models.ChangeRequest)
admin.site.register(models.Board)
admin.site.register(models.BoardColumn)
admin.site.register(models.TaskBoardPosition)
admin.site.register(models.HealthRule)
admin.site.register(models.HealthSnapshot)
admin.site.register(models.Risk)
admin.site.register(models.Issue)
admin.site.register(models.TechnicalBrief)
admin.site.register(models.TechnicalBriefVersion)
admin.site.register(models.Requirement)
admin.site.register(models.AcceptanceCriteria)
admin.site.register(models.ResourceRequest)
admin.site.register(models.ResourceRequestLine)
admin.site.register(models.ResourceAllocation)
admin.site.register(models.ProgressSnapshot)
admin.site.register(models.EquipmentUsage)
admin.site.register(models.WeightIndicator)
admin.site.register(models.WeightComponent)
