# Generated by Django 5.2.17 on 2026-08-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0002_initial'),
        ('inventory', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0001_initial'),
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, default='', max_length=255)),
                ('billing_frequency', models.CharField(blank=True, default='', max_length=255)),
                ('order_frequency', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_contract_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_contract_document_set', to='core.businessdocument')),
            ],
            options={
                'db_table': 'sales_contract',
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contracted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_contractline_contract_set', to='sales.contract')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_contractline_product_set', to='master_data.product')),
                ('tax_code', models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_contractline_tax_code_set', to='master_data.taxcode')),
            ],
            options={
                'db_table': 'sales_contract_line',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_contract_set', to='sales.contract')),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_currency_set', to='master_data.currency')),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_document_set', to='core.businessdocument')),
                ('payment_term', models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_payment_term_set', to='master_data.paymentterm')),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=255)),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_delivery_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_delivery_document_set', to='core.businessdocument')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_delivery_warehouse_set', to='master_data.warehouse')),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_delivery_sales_order_set', to='sales.order')),
            ],
            options={
                'db_table': 'sales_delivery',
            },
        ),
        migrations.CreateModel(
            name='OrderChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(blank=True, default='', max_length=255)),
                ('change_reason', models.CharField(blank=True, default='', max_length=255)),
                ('value_impact', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('schedule_impact_days', models.IntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderchangerequest_document_set', to='core.businessdocument')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderchangerequest_project_set', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderchangerequest_requested_by_set', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderchangerequest_sales_order_set', to='sales.order')),
            ],
            options={
                'db_table': 'sales_order_change_request',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('invoiced_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('fulfillment_method', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderline_product_set', to='master_data.product')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderline_project_set', to='projects.project')),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderline_sales_order_set', to='sales.order')),
                ('tax_code', models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderline_tax_code_set', to='master_data.taxcode')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orderline_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'sales_order_line',
            },
        ),
        migrations.CreateModel(
            name='DemandSupplyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demand_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('fulfilled_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('production_order', models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_demandsupplylink_production_order_set', to='manufacturing.productionorder')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_demandsupplylink_project_set', to='projects.project')),
                ('purchase_order_line', models.ForeignKey(blank=True, db_column='purchase_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_demandsupplylink_purchase_order_line_set', to='procurement.purchaseorderline')),
                ('stock_reservation', models.ForeignKey(blank=True, db_column='stock_reservation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_demandsupplylink_stock_reservation_set', to='inventory.stockreservation')),
                ('sales_order_line', models.ForeignKey(blank=True, db_column='sales_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_demandsupplylink_sales_order_line_set', to='sales.orderline')),
            ],
            options={
                'db_table': 'sales_demand_supply_link',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('delivery', models.ForeignKey(blank=True, db_column='delivery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_delivery_set', to='sales.delivery')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_lot_set', to='inventory.lot')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_product_set', to='master_data.product')),
                ('serial_number', models.ForeignKey(blank=True, db_column='serial_number_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_serial_number_set', to='inventory.serialnumber')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_uom_set', to='master_data.uom')),
                ('sales_order_line', models.ForeignKey(blank=True, db_column='sales_order_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_deliveryline_sales_order_line_set', to='sales.orderline')),
            ],
            options={
                'db_table': 'sales_delivery_line',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('estimated_total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('estimated_margin', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_currency_set', to='master_data.currency')),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_customer_party_set', to='master_data.party')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_document_set', to='core.businessdocument')),
                ('opportunity', models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_opportunity_set', to='crm.opportunity')),
                ('payment_term', models.ForeignKey(blank=True, db_column='payment_term_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_payment_term_set', to='master_data.paymentterm')),
            ],
            options={
                'db_table': 'sales_quotation',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quotation',
            field=models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_quotation_set', to='sales.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotationline_product_set', to='master_data.product')),
                ('quotation', models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotationline_quotation_set', to='sales.quotation')),
                ('tax_code', models.ForeignKey(blank=True, db_column='tax_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotationline_tax_code_set', to='master_data.taxcode')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotationline_uom_set', to='master_data.uom')),
            ],
            options={
                'db_table': 'sales_quotation_line',
            },
        ),
        migrations.CreateModel(
            name='QuotationCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_element', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('calculation_source', models.CharField(blank=True, default='', max_length=255)),
                ('quotation_line', models.ForeignKey(blank=True, db_column='quotation_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotationcost_quotation_line_set', to='sales.quotationline')),
            ],
            options={
                'db_table': 'sales_quotation_cost',
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=255)),
                ('next_order_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_create', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_recurringorderrule_contract_set', to='sales.contract')),
                ('customer_party', models.ForeignKey(blank=True, db_column='customer_party_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_recurringorderrule_customer_party_set', to='master_data.party')),
                ('source_sales_order', models.ForeignKey(blank=True, db_column='source_sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_recurringorderrule_source_sales_order_set', to='sales.order')),
            ],
            options={
                'db_table': 'sales_recurring_order_rule',
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('run_status', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('generated_sales_order', models.ForeignKey(blank=True, db_column='generated_sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_recurringorderrun_generated_sales_order_set', to='sales.order')),
                ('recurring_order_rule', models.ForeignKey(blank=True, db_column='recurring_order_rule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_recurringorderrun_recurring_order_rule_set', to='sales.recurringorderrule')),
            ],
            options={
                'db_table': 'sales_recurring_order_run',
            },
        ),
    ]
